/**
 * Transfer object created from Java object au.com.smartcommons.common.entity.embeddable.Address
 * Generated by Maven. See Java class GenerateTypeScript.
 */
interface Address {
    address1: string;
    address2?: string;
    city: string;
    country?: string;
    postcode: string;
    state: string;
}
export default Address;
