/**
 * Smart Health Admin Permssion constants
 * Generated by Maven. See Java class GenerateTypeScript.
 */
declare enum AdminPermission {
    AdminAddUserToMedicalGroup = 1,
    AdminAssignSmartcard = 14,
    AdminConnectwithPAS = 27,
    CreateMedicalGroup = 2,
    AdminCreateUser = 34,
    CreateUser = 4,
    LinktoMyHR = 28,
    MergePatients = 20,
    AdminModifyMedicalGroup = 6,
    AdminModifyMedicalGroupList = 25,
    AdminModifyMedicalGroupPrivateKeys = 32,
    AdminModifyNotificationAlertTypes = 22,
    AdminModifyUserDetails = 9,
    AdminModifyUserPermissions = 10,
    OpenPatientforAdmin = 33,
    PrintReports = 16,
    AdminRemoveUserFromMedicalGroup = 13,
    AdminValidateHPII = 30,
    AdminValidateHPIO = 31,
    ValidateIHI = 29,
    AdminViewalertsforMedicalGroup = 23
}
export default AdminPermission;
