"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
/**
 * Smart Health Admin Permssion constants
 * Generated by Maven. See Java class GenerateTypeScript.
 */
var AdminPermission;
(function (AdminPermission) {
    AdminPermission[AdminPermission["AdminAddUserToMedicalGroup"] = 1] = "AdminAddUserToMedicalGroup";
    AdminPermission[AdminPermission["AdminAssignSmartcard"] = 14] = "AdminAssignSmartcard";
    AdminPermission[AdminPermission["AdminConnectwithPAS"] = 27] = "AdminConnectwithPAS";
    AdminPermission[AdminPermission["CreateMedicalGroup"] = 2] = "CreateMedicalGroup";
    AdminPermission[AdminPermission["AdminCreateUser"] = 34] = "AdminCreateUser";
    AdminPermission[AdminPermission["CreateUser"] = 4] = "CreateUser";
    AdminPermission[AdminPermission["LinktoMyHR"] = 28] = "LinktoMyHR";
    AdminPermission[AdminPermission["MergePatients"] = 20] = "MergePatients";
    AdminPermission[AdminPermission["AdminModifyMedicalGroup"] = 6] = "AdminModifyMedicalGroup";
    AdminPermission[AdminPermission["AdminModifyMedicalGroupList"] = 25] = "AdminModifyMedicalGroupList";
    AdminPermission[AdminPermission["AdminModifyMedicalGroupPrivateKeys"] = 32] = "AdminModifyMedicalGroupPrivateKeys";
    AdminPermission[AdminPermission["AdminModifyNotificationAlertTypes"] = 22] = "AdminModifyNotificationAlertTypes";
    AdminPermission[AdminPermission["AdminModifyUserDetails"] = 9] = "AdminModifyUserDetails";
    AdminPermission[AdminPermission["AdminModifyUserPermissions"] = 10] = "AdminModifyUserPermissions";
    AdminPermission[AdminPermission["OpenPatientforAdmin"] = 33] = "OpenPatientforAdmin";
    AdminPermission[AdminPermission["PrintReports"] = 16] = "PrintReports";
    AdminPermission[AdminPermission["AdminRemoveUserFromMedicalGroup"] = 13] = "AdminRemoveUserFromMedicalGroup";
    AdminPermission[AdminPermission["AdminValidateHPII"] = 30] = "AdminValidateHPII";
    AdminPermission[AdminPermission["AdminValidateHPIO"] = 31] = "AdminValidateHPIO";
    AdminPermission[AdminPermission["ValidateIHI"] = 29] = "ValidateIHI";
    AdminPermission[AdminPermission["AdminViewalertsforMedicalGroup"] = 23] = "AdminViewalertsforMedicalGroup";
})(AdminPermission || (AdminPermission = {}));
exports.default = AdminPermission;
//# sourceMappingURL=AdminPermissions.js.map