/**
 * Typescript enum from the Java enum of the same name
 *
 * Aboriginal/Torres Strait Islander status
 *
 * Generated by Maven. See Java class GenerateTypeScript.
 */
declare enum ATSI {
    Aboriginal = "Aboriginal",
    TSI = "TSI",
    AboriginalAndTSI = "AboriginalAndTSI",
    NeitherAboriginalNorTSI = "NeitherAboriginalNorTSI"
}
export declare const aTSIDescriptions: {
    Aboriginal: string;
    TSI: string;
    AboriginalAndTSI: string;
    NeitherAboriginalNorTSI: string;
};
export default ATSI;
