// "use strict";
Object.defineProperty(exports, "__esModule", { value: true });
/**
 * Typescript enum from the Java enum of the same name
 *
 * Aboriginal/Torres Strait Islander status
 *
 * Generated by Maven. See Java class GenerateTypeScript.
 */
var ATSI;
(function (ATSI) {
    ATSI["Aboriginal"] = "Aboriginal";
    ATSI["TSI"] = "TSI";
    ATSI["AboriginalAndTSI"] = "AboriginalAndTSI";
    ATSI["NeitherAboriginalNorTSI"] = "NeitherAboriginalNorTSI";
})(ATSI || (ATSI = {}));
exports.aTSIDescriptions = {
    Aboriginal: 'Aboriginal but not TSI',
    TSI: 'TSI but not Aboriginal',
    AboriginalAndTSI: 'Both Aboriginal and TSI',
    NeitherAboriginalNorTSI: 'Neither Aboriginal nor TSI',
};
exports.default = ATSI;
//# sourceMappingURL=ATSI.js.map