/**
 * Transfer object created from Java object au.com.smartcommons.common.entity.audit.AuditSH
 * Generated by Maven. See Java class GenerateTypeScript.
 */
interface Audit {
    auditIPAddress: string;
    auditDateTime: Date;
    auditMedicalGroupId: number;
    auditUserId: number;
}
export default Audit;
