/**
 * Transfer object created from Java object au.com.smartcommons.common.entity.embeddable.BusinessContactDetails
 * Generated by Maven. See Java class GenerateTypeScript.
 */
interface BusinessContactDetails {
    email: string;
    fax: string;
    phone: string;
}
export default BusinessContactDetails;
