/**
 * Transfer object created from Java object au.com.smarthealth.server.rest.webui.data.ChildPughClassParameters
 * Generated by Maven. See Java class GenerateTypeScript.
 */
interface ChildPughClassParameters {
    albumin?: number;
    albuminUnits?: string;
    ascites?: string;
    bilirubin?: number;
    bilirubinUnits?: string;
    encephalopathy?: string;
    inr?: number;
}
export default ChildPughClassParameters;
