/**
 * Smart Health Clinical Permssion constants, exclusing service permissions
 * Generated by Maven. See Java class GenerateTypeScript.
 */
declare enum ClinicalPermission {
    FinishMeetings = 635,
    ModifyAddLatePatient = 630,
    ModifyAddPatient = 678,
    ModifyMeetings = 538,
    ViewMeetings = 537,
    CreatePatient = 1,
    DeleteGenogram = 295,
    DownloadGenogram = 294,
    EmergencyOpenPatient = 448,
    ModifyDatafromPAS = 693,
    ModifyDemographicDetails = 4,
    ModifyFamilySocial = 594,
    ModifyHealthInsuranceDetails = 6,
    ModifyProvidersAndConsents = 462,
    ModifySummaryClinicalData = 5,
    SearchPatient = 98,
    UploadGenogram = 293,
    ViewAlerts = 10,
    ViewDemographicDetails = 7,
    ViewFamilySocial = 595,
    ViewHealthInsuranceDetails = 9,
    ViewProvidersAndConsents = 463,
    ViewSummaryClinicalData = 8,
    PatientWatchImportCSV = 679,
    PatientWatchSaveCSV = 700,
    ViewHealthCoachPatientWatchPatientList = 645,
    ViewTeleCareGuidePatientWatchPatientList = 689,
    ViewClinicalMeasures = 356,
    ViewLungFunctionSummary = 348,
    ViewMedications = 316,
    ViewPathologySummary = 335,
    ViewRenalPathologySummary = 664,
    ViewRenalTransplantPathologySummary = 665
}
export declare const ClinicalPermissionViewAnyPatientList: ClinicalPermission[];
export default ClinicalPermission;
