"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
/**
 * Smart Health Clinical Permssion constants, exclusing service permissions
 * Generated by Maven. See Java class GenerateTypeScript.
 */
var ClinicalPermission;
(function (ClinicalPermission) {
    // Permissions for category Meetings
    ClinicalPermission[ClinicalPermission["FinishMeetings"] = 635] = "FinishMeetings";
    ClinicalPermission[ClinicalPermission["ModifyAddLatePatient"] = 630] = "ModifyAddLatePatient";
    ClinicalPermission[ClinicalPermission["ModifyAddPatient"] = 678] = "ModifyAddPatient";
    ClinicalPermission[ClinicalPermission["ModifyMeetings"] = 538] = "ModifyMeetings";
    ClinicalPermission[ClinicalPermission["ViewMeetings"] = 537] = "ViewMeetings";
    // Permissions for category Patient
    ClinicalPermission[ClinicalPermission["CreatePatient"] = 1] = "CreatePatient";
    ClinicalPermission[ClinicalPermission["DeleteGenogram"] = 295] = "DeleteGenogram";
    ClinicalPermission[ClinicalPermission["DownloadGenogram"] = 294] = "DownloadGenogram";
    ClinicalPermission[ClinicalPermission["EmergencyOpenPatient"] = 448] = "EmergencyOpenPatient";
    ClinicalPermission[ClinicalPermission["ModifyDatafromPAS"] = 693] = "ModifyDatafromPAS";
    ClinicalPermission[ClinicalPermission["ModifyDemographicDetails"] = 4] = "ModifyDemographicDetails";
    ClinicalPermission[ClinicalPermission["ModifyFamilySocial"] = 594] = "ModifyFamilySocial";
    ClinicalPermission[ClinicalPermission["ModifyHealthInsuranceDetails"] = 6] = "ModifyHealthInsuranceDetails";
    ClinicalPermission[ClinicalPermission["ModifyProvidersAndConsents"] = 462] = "ModifyProvidersAndConsents";
    ClinicalPermission[ClinicalPermission["ModifySummaryClinicalData"] = 5] = "ModifySummaryClinicalData";
    ClinicalPermission[ClinicalPermission["SearchPatient"] = 98] = "SearchPatient";
    ClinicalPermission[ClinicalPermission["UploadGenogram"] = 293] = "UploadGenogram";
    ClinicalPermission[ClinicalPermission["ViewAlerts"] = 10] = "ViewAlerts";
    ClinicalPermission[ClinicalPermission["ViewDemographicDetails"] = 7] = "ViewDemographicDetails";
    ClinicalPermission[ClinicalPermission["ViewFamilySocial"] = 595] = "ViewFamilySocial";
    ClinicalPermission[ClinicalPermission["ViewHealthInsuranceDetails"] = 9] = "ViewHealthInsuranceDetails";
    ClinicalPermission[ClinicalPermission["ViewProvidersAndConsents"] = 463] = "ViewProvidersAndConsents";
    ClinicalPermission[ClinicalPermission["ViewSummaryClinicalData"] = 8] = "ViewSummaryClinicalData";
    // Permissions for category PatientList
    ClinicalPermission[ClinicalPermission["PatientWatchImportCSV"] = 679] = "PatientWatchImportCSV";
    ClinicalPermission[ClinicalPermission["PatientWatchSaveCSV"] = 700] = "PatientWatchSaveCSV";
    ClinicalPermission[ClinicalPermission["ViewHealthCoachPatientWatchPatientList"] = 645] = "ViewHealthCoachPatientWatchPatientList";
    ClinicalPermission[ClinicalPermission["ViewTeleCareGuidePatientWatchPatientList"] = 689] = "ViewTeleCareGuidePatientWatchPatientList";
    // Permissions for category Summary
    ClinicalPermission[ClinicalPermission["ViewClinicalMeasures"] = 356] = "ViewClinicalMeasures";
    ClinicalPermission[ClinicalPermission["ViewLungFunctionSummary"] = 348] = "ViewLungFunctionSummary";
    ClinicalPermission[ClinicalPermission["ViewMedications"] = 316] = "ViewMedications";
    ClinicalPermission[ClinicalPermission["ViewPathologySummary"] = 335] = "ViewPathologySummary";
    ClinicalPermission[ClinicalPermission["ViewRenalPathologySummary"] = 664] = "ViewRenalPathologySummary";
    ClinicalPermission[ClinicalPermission["ViewRenalTransplantPathologySummary"] = 665] = "ViewRenalTransplantPathologySummary";
})(ClinicalPermission || (ClinicalPermission = {}));
exports.ClinicalPermissionViewAnyPatientList = [ClinicalPermission.ViewHealthCoachPatientWatchPatientList, ClinicalPermission.ViewTeleCareGuidePatientWatchPatientList];
exports.default = ClinicalPermission;
//# sourceMappingURL=ClinicalPermission.js.map