/**
 * Transfer object created from Java object au.com.smartcommons.common.entity.embeddable.CodedValue
 * Generated by Maven. See Java class GenerateTypeScript.
 */
interface CodedValue {
    code?: string;
    codeSet?: string;
    value: string;
}
export default CodedValue;
