/**
 * Typescript enum from the Java enum of the same name
 * Generated by Maven. See Java class GenerateTypeScript.
 */
declare enum Confidentiality {
    Normal = "Normal",
    Restricted = "Restricted",
    VeryRestricted = "VeryRestricted"
}
export declare const confidentialityDescriptions: {
    Normal: string;
    Restricted: string;
    VeryRestricted: string;
};
export default Confidentiality;
