"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
/**
 * Typescript enum from the Java enum of the same name
 * Generated by Maven. See Java class GenerateTypeScript.
 */
var Confidentiality;
(function (Confidentiality) {
    Confidentiality["Normal"] = "Normal";
    Confidentiality["Restricted"] = "Restricted";
    Confidentiality["VeryRestricted"] = "VeryRestricted";
})(Confidentiality || (Confidentiality = {}));
exports.confidentialityDescriptions = {
    Normal: 'Normal',
    Restricted: 'Restricted',
    VeryRestricted: 'Very Restricted',
};
exports.default = Confidentiality;
//# sourceMappingURL=Confidentiality.js.map