import EntityType from './EntityType';
/**
 * Transfer object created from Java object au.com.smarthealth.server.rest.data.EntityReference
 * Generated by Maven. See Java class GenerateTypeScript.
 */
interface EntityReference {
    associatedID?: any;
    id: any;
    type: EntityType;
}
export default EntityReference;
