/**
 * Generalised data for an entity. Usually derived from a form description. In TypeScript this is an object  and in Java this is a Map.
 * Generated by Maven. See Java class GenerateTypeScript.
 */
declare type EntityData = {
    [key: string]: any;
};
export default EntityData;
