/**
 * Typescript enum from the Java enum of the same name
 * Generated by Maven. See Java class GenerateTypeScript.
 */
declare enum EntityType {
    EntityReferenceList = "EntityReferenceList",
    EntityUpdateList = "EntityUpdateList",
    FormDescription = "FormDescription",
    MedicalGroup = "MedicalGroup",
    MedicalGroupList = "MedicalGroupList",
    MedicalGroupMember = "MedicalGroupMember",
    MedicationSummary = "MedicationSummary",
    Observations = "Observations",
    Patient = "Patient",
    PatientClinical = "PatientClinical",
    PatientContacts = "PatientContacts",
    PatientFamilySocial = "PatientFamilySocial",
    PatientIdentifiers = "PatientIdentifiers",
    PatientMedicalGroupAssociation = "PatientMedicalGroupAssociation",
    PatientPAS = "PatientPAS",
    PatientProviderAssociation = "PatientProviderAssociation",
    Pathology = "Pathology",
    ServiceRecord = "ServiceRecord",
    ServiceType = "ServiceType",
    Summary = "Summary",
    User = "User",
    ValueSet = "ValueSet"
}
export default EntityType;
