import EntityReference from './EntityReference';
/**
 * Transfer object created from Java object au.com.smarthealth.server.rest.data.EntityUpdate
 *
 * An entity to update with the /entities REST call
 *
 * Generated by Maven. See Java class GenerateTypeScript.
 */
interface EntityUpdate {
    /** Needs to correspond to the type in entityReference */
    entity: any;
    entityReference: EntityReference;
}
export default EntityUpdate;
