import EntityType from './EntityType';
/**
 * Transfer object created from Java object au.com.smarthealth.server.rest.data.EntityUpdateList
 *
 * A list of entities to update
 *
 * Generated by Maven. See Java class GenerateTypeScript.
 */
interface EntityUpdateList<T> {
    /** List entries need to correspond to the EntityType */
    entities: T[];
    type: EntityType;
}
export default EntityUpdateList;
