/**
 * Typescript enum from the Java enum of the same name
 * Generated by Maven. See Java class GenerateTypeScript.
 */
declare enum EntityReferenceListType {
    MedicalGroupAssociations = "MedicalGroupAssociations",
    MedicalGroupMemberRecents = "MedicalGroupMemberRecents",
    MedicalGroupRecents = "MedicalGroupRecents",
    MedicationHistoryByCode = "MedicationHistoryByCode",
    MedicationHistoryByName = "MedicationHistoryByName",
    MedicationsLatest = "MedicationsLatest",
    MembersOfMedicalGroup = "MembersOfMedicalGroup"
}
export default EntityReferenceListType;
