"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var EntityReferenceListType_1 = require("./EntityReferenceListType");
var EntityType_1 = require("./EntityType");
/**
 * Typescript helper for generating EntityReferenceList ids.
 * Derived from EntityReferenceListType.java
 * Generated by Maven. See Java class GenerateTypeScript.
 */
var EntityReferenceListTypeUtility = /** @class */ (function () {
    function EntityReferenceListTypeUtility() {
    }
    EntityReferenceListTypeUtility.getTemplate = function (type) {
        switch (type) {
            case EntityReferenceListType_1.default.MedicalGroupAssociations:
                return '/patients/{patientID}/medicalgroups';
            case EntityReferenceListType_1.default.MedicalGroupMemberRecents:
                return '/medicalgroupmembers/recents';
            case EntityReferenceListType_1.default.MedicalGroupRecents:
                return '/medicalgroups/recents';
            case EntityReferenceListType_1.default.MedicationHistoryByCode:
                return '/medications/history?productCode={id}';
            case EntityReferenceListType_1.default.MedicationHistoryByName:
                return '/medications/history?name={name}';
            case EntityReferenceListType_1.default.MedicationsLatest:
                return '/medications/latest';
            case EntityReferenceListType_1.default.MembersOfMedicalGroup:
                return '/medicalgroups/{groupID}/members';
        }
        throw new Error();
    };
    EntityReferenceListTypeUtility.buildID = function (type, params) {
        var id = EntityReferenceListTypeUtility.getTemplate(type);
        if (params) {
            id = id.replace('{groupID}', params['groupID']);
            id = id.replace('{id}', params['id']);
            id = id.replace('{name}', params['name']);
            id = id.replace('{patientID}', params['patientID']);
        }
        return id;
    };
    EntityReferenceListTypeUtility.buildEntityReference = function (type, params) {
        return { id: EntityReferenceListTypeUtility.buildID(type, params), type: EntityType_1.default.EntityReferenceList };
    };
    return EntityReferenceListTypeUtility;
}());
exports.default = EntityReferenceListTypeUtility;
//# sourceMappingURL=EntityReferenceListTypeUtility.js.map