"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
/**
 * Typescript enum from the Java enum of the same name
 * Generated by Maven. See Java class GenerateTypeScript.
 */
var EntityReferenceListType;
(function (EntityReferenceListType) {
    EntityReferenceListType["MedicalGroupAssociations"] = "MedicalGroupAssociations";
    EntityReferenceListType["MedicalGroupMemberRecents"] = "MedicalGroupMemberRecents";
    EntityReferenceListType["MedicalGroupRecents"] = "MedicalGroupRecents";
    EntityReferenceListType["MedicationHistoryByCode"] = "MedicationHistoryByCode";
    EntityReferenceListType["MedicationHistoryByName"] = "MedicationHistoryByName";
    EntityReferenceListType["MedicationsLatest"] = "MedicationsLatest";
    EntityReferenceListType["MembersOfMedicalGroup"] = "MembersOfMedicalGroup";
})(EntityReferenceListType || (EntityReferenceListType = {}));
exports.default = EntityReferenceListType;
//# sourceMappingURL=EntityReferenceListType.js.map