"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
/**
 * Typescript enum from the Java enum of the same name
 * Generated by Maven. See Java class GenerateTypeScript.
 */
var EntityType;
(function (EntityType) {
    EntityType["EntityReferenceList"] = "EntityReferenceList";
    EntityType["EntityUpdateList"] = "EntityUpdateList";
    EntityType["FormDescription"] = "FormDescription";
    EntityType["MedicalGroup"] = "MedicalGroup";
    EntityType["MedicalGroupList"] = "MedicalGroupList";
    EntityType["MedicalGroupMember"] = "MedicalGroupMember";
    EntityType["MedicationSummary"] = "MedicationSummary";
    EntityType["Observations"] = "Observations";
    EntityType["Patient"] = "Patient";
    EntityType["PatientClinical"] = "PatientClinical";
    EntityType["PatientContacts"] = "PatientContacts";
    EntityType["PatientFamilySocial"] = "PatientFamilySocial";
    EntityType["PatientIdentifiers"] = "PatientIdentifiers";
    EntityType["PatientMedicalGroupAssociation"] = "PatientMedicalGroupAssociation";
    EntityType["PatientPAS"] = "PatientPAS";
    EntityType["PatientProviderAssociation"] = "PatientProviderAssociation";
    EntityType["Pathology"] = "Pathology";
    EntityType["ServiceRecord"] = "ServiceRecord";
    EntityType["ServiceType"] = "ServiceType";
    EntityType["Summary"] = "Summary";
    EntityType["User"] = "User";
    EntityType["ValueSet"] = "ValueSet";
})(EntityType || (EntityType = {}));
exports.default = EntityType;
//# sourceMappingURL=EntityType.js.map