/**
 * Transfer object created from Java object au.com.smartcommons.common.datetime.EventDateTime
 * Generated by Maven. See Java class GenerateTypeScript.
 */
interface EventDateTime {
    iso: string;
}
export default EventDateTime;
