/**
 * Typescript enum from the Java enum of the same name
 * Generated by Maven. See Java class GenerateTypeScript.
 */
declare enum FieldTableActionMode {
    Both = "Both",
    Edit = "Edit",
    View = "View"
}
export default FieldTableActionMode;
