import FieldCondition from './FieldCondition';
/**
 * Transfer object created from Java object au.com.smarthealth.server.rest.form.FieldConditionOr
 * Generated by Maven. See Java class GenerateTypeScript.
 */
interface FieldConditionOr {
    or: FieldCondition[];
}
export default FieldConditionOr;
