import FieldLabelPosition from './FieldLabelPosition';
/**
 * Transfer object created from Java object au.com.smarthealth.server.rest.form.FieldLayout
 * Generated by Maven. See Java class GenerateTypeScript.
 */
interface FieldLayout {
    alignTop?: boolean;
    fillHeight?: boolean;
    fillWidth?: boolean;
    labelPosition: FieldLabelPosition;
    newLine?: boolean;
    skip?: number;
    span?: number;
    spanLine?: boolean;
}
export default FieldLayout;
