"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
/**
 * Typescript enum from the Java enum of the same name
 * Generated by Maven. See Java class GenerateTypeScript.
 */
var FieldLabelPosition;
(function (FieldLabelPosition) {
    FieldLabelPosition["Above"] = "Above";
    FieldLabelPosition["Before"] = "Before";
    FieldLabelPosition["BeforeTop"] = "BeforeTop";
    FieldLabelPosition["Omit"] = "Omit";
})(FieldLabelPosition || (FieldLabelPosition = {}));
exports.default = FieldLabelPosition;
//# sourceMappingURL=FieldLabelPosition.js.map