import FieldConditionAnd from './FieldConditionAnd';
import FieldConditionField from './FieldConditionField';
import FieldConditionNot from './FieldConditionNot';
import FieldConditionOr from './FieldConditionOr';
/**
 * Visitor for Form Fields
 * Generated by Maven. See Java class GenerateTypeScript.
 */
interface FieldConditionVisitor<T> {
    visitFieldConditionAnd(field: FieldConditionAnd): T;
    visitFieldConditionField(field: FieldConditionField): T;
    visitFieldConditionNot(field: FieldConditionNot): T;
    visitFieldConditionOr(field: FieldConditionOr): T;
}
export default FieldConditionVisitor;
