/**
 * Transfer object created from Java object au.com.smarthealth.server.rest.form.FieldConditionField
 * Generated by Maven. See Java class GenerateTypeScript.
 */
interface FieldConditionField {
    equals?: string[];
    fieldID: string;
    testDisabled?: boolean;
    testEmpty?: boolean;
    testEnabled?: boolean;
    testFalse?: boolean;
    testMandatory?: boolean;
    testNotEmpty?: boolean;
    testTrue?: boolean;
    testValid?: boolean;
}
export default FieldConditionField;
