import FieldCondition from './FieldCondition';
/**
 * Transfer object created from Java object au.com.smarthealth.server.rest.form.FieldConditionNot
 * Generated by Maven. See Java class GenerateTypeScript.
 */
interface FieldConditionNot {
    not: FieldCondition;
}
export default FieldConditionNot;
