/**
 * Typescript enum from the Java enum of the same name
 * Generated by Maven. See Java class GenerateTypeScript.
 */
declare enum FieldTableActionType {
    OpenService = "OpenService"
}
export default FieldTableActionType;
