import FieldCondition from './FieldCondition';
import FieldState from './FieldState';
/**
 * Transfer object created from Java object au.com.smarthealth.server.rest.form.FieldConditionalIf
 * Generated by Maven. See Java class GenerateTypeScript.
 */
interface FieldConditionalIf {
    condition: FieldCondition;
    then: FieldState;
}
export default FieldConditionalIf;
