/**
 * Typescript enum from the Java enum of the same name
 * Generated by Maven. See Java class GenerateTypeScript.
 */
declare enum FieldEditState {
    Enabled = "Enabled",
    Hidden = "Hidden",
    Mandatory = "Mandatory",
    ReadOnly = "ReadOnly"
}
export default FieldEditState;
