import FieldCalculationType from './FieldCalculationType';
/**
 * Transfer object created from Java object au.com.smarthealth.server.rest.form.FieldCalculation
 * Generated by Maven. See Java class GenerateTypeScript.
 */
interface FieldCalculation {
    paramFieldIDs: string[];
    type: FieldCalculationType;
}
export default FieldCalculation;
