import FieldEditState from './FieldEditState';
/**
 * Transfer object created from Java object au.com.smarthealth.common.conditional.FieldState
 * Generated by Maven. See Java class GenerateTypeScript.
 */
interface FieldState {
    clearValue?: boolean;
    editState: FieldEditState;
    viewStateHidden?: boolean;
}
export default FieldState;
