/**
 * Typescript enum from the Java enum of the same name
 * Generated by Maven. See Java class GenerateTypeScript.
 */
declare enum FieldCalculationType {
    BMI = "BMI",
    DIFFERENCE_IN_DAYS = "DIFFERENCE_IN_DAYS",
    DIFFERENCE_IN_HOURS = "DIFFERENCE_IN_HOURS",
    DIFFERENCE_IN_MINUTES = "DIFFERENCE_IN_MINUTES",
    DIFFERENCE_IN_MONTHS = "DIFFERENCE_IN_MONTHS"
}
export default FieldCalculationType;
