import FieldConditionAnd from './FieldConditionAnd';
import FieldConditionField from './FieldConditionField';
import FieldConditionNot from './FieldConditionNot';
import FieldConditionOr from './FieldConditionOr';
/**
 * Transfer object created from Java object of the same name
 * Generated by Maven. See Java class GenerateTypeScript.
 */
declare type FieldCondition = FieldConditionAnd | FieldConditionField | FieldConditionNot | FieldConditionOr;
export default FieldCondition;
