"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
/**
 * Typescript enum from the Java enum of the same name
 * Generated by Maven. See Java class GenerateTypeScript.
 */
var FieldTableActionType;
(function (FieldTableActionType) {
    FieldTableActionType["OpenService"] = "OpenService";
})(FieldTableActionType || (FieldTableActionType = {}));
exports.default = FieldTableActionType;
//# sourceMappingURL=FieldTableActionType.js.map