"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
/**
 * Typescript enum from the Java enum of the same name
 * Generated by Maven. See Java class GenerateTypeScript.
 */
var FieldTableActionMode;
(function (FieldTableActionMode) {
    FieldTableActionMode["Both"] = "Both";
    FieldTableActionMode["Edit"] = "Edit";
    FieldTableActionMode["View"] = "View";
})(FieldTableActionMode || (FieldTableActionMode = {}));
exports.default = FieldTableActionMode;
//# sourceMappingURL=FieldTableActionMode.js.map