"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
/**
 * Typescript enum from the Java enum of the same name
 * Generated by Maven. See Java class GenerateTypeScript.
 */
var FieldEditState;
(function (FieldEditState) {
    FieldEditState["Enabled"] = "Enabled";
    FieldEditState["Hidden"] = "Hidden";
    FieldEditState["Mandatory"] = "Mandatory";
    FieldEditState["ReadOnly"] = "ReadOnly";
})(FieldEditState || (FieldEditState = {}));
exports.default = FieldEditState;
//# sourceMappingURL=FieldEditState.js.map