import FieldTableActionMode from './FieldTableActionMode';
import FieldTableActionType from './FieldTableActionType';
/**
 * Transfer object created from Java object au.com.smarthealth.server.rest.form.FieldTableAction
 * Generated by Maven. See Java class GenerateTypeScript.
 */
interface FieldTableAction {
    mode: FieldTableActionMode;
    refFieldID: string;
    type: FieldTableActionType;
}
export default FieldTableAction;
