import FieldCondition from './FieldCondition';
/**
 * Transfer object created from Java object au.com.smarthealth.server.rest.form.FieldConditionAnd
 * Generated by Maven. See Java class GenerateTypeScript.
 */
interface FieldConditionAnd {
    and: FieldCondition[];
}
export default FieldConditionAnd;
