"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
/**
 * Typescript enum from the Java enum of the same name
 * Generated by Maven. See Java class GenerateTypeScript.
 */
var FieldCalculationType;
(function (FieldCalculationType) {
    FieldCalculationType["BMI"] = "BMI";
    FieldCalculationType["DIFFERENCE_IN_DAYS"] = "DIFFERENCE_IN_DAYS";
    FieldCalculationType["DIFFERENCE_IN_HOURS"] = "DIFFERENCE_IN_HOURS";
    FieldCalculationType["DIFFERENCE_IN_MINUTES"] = "DIFFERENCE_IN_MINUTES";
    FieldCalculationType["DIFFERENCE_IN_MONTHS"] = "DIFFERENCE_IN_MONTHS";
})(FieldCalculationType || (FieldCalculationType = {}));
exports.default = FieldCalculationType;
//# sourceMappingURL=FieldCalculationType.js.map