/**
 * Typescript enum from the Java enum of the same name
 * Generated by Maven. See Java class GenerateTypeScript.
 */
declare enum FieldLabelPosition {
    Above = "Above",
    Before = "Before",
    BeforeTop = "BeforeTop",
    Omit = "Omit"
}
export default FieldLabelPosition;
