/**
 * Typescript enum from the Java enum of the same name
 * Generated by Maven. See Java class GenerateTypeScript.
 */
declare enum FilteredPathologyType {
    Renal = "Renal",
    RenalTransplant = "RenalTransplant"
}
export default FilteredPathologyType;
