import PathologyResultAndServiceAtDate from './PathologyResultAndServiceAtDate';
import FilteredPathologyType from './FilteredPathologyType';
/**
 * Transfer object created from Java object au.com.smarthealth.common.services.pathology.FilteredPathologySummaryData
 * Generated by Maven. See Java class GenerateTypeScript.
 */
interface FilteredPathologySummaryData {
    results: PathologyResultAndServiceAtDate[];
    resultTypes: string[];
    someValuesOmmited?: boolean;
    type: FilteredPathologyType;
}
export default FilteredPathologySummaryData;
