"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
/**
 * Typescript enum from the Java enum of the same name
 * Generated by Maven. See Java class GenerateTypeScript.
 */
var FilteredPathologyType;
(function (FilteredPathologyType) {
    FilteredPathologyType["Renal"] = "Renal";
    FilteredPathologyType["RenalTransplant"] = "RenalTransplant";
})(FilteredPathologyType || (FilteredPathologyType = {}));
exports.default = FilteredPathologyType;
//# sourceMappingURL=FilteredPathologyType.js.map