import FormFieldOrSection from './FormFieldOrSection';
/**
 * Transfer object created from Java object au.com.smarthealth.server.rest.form.FormTab
 * Generated by Maven. See Java class GenerateTypeScript.
 */
interface FormTab {
    id: string;
    sections: FormFieldOrSection[];
    title: string;
}
export default FormTab;
