import FormTab from './FormTab';
/**
 * Transfer object created from Java object au.com.smarthealth.server.rest.form.FormTabs
 * Generated by Maven. See Java class GenerateTypeScript.
 */
interface FormTabs {
    tabs: FormTab[];
}
export default FormTabs;
