/**
 * Transfer object created from Java object au.com.smarthealth.server.rest.form.FormBehaviour
 * Generated by Maven. See Java class GenerateTypeScript.
 */
interface FormBehaviour {
    attachments?: boolean;
    mostRecentOnlyEditable?: boolean;
    newServiceButton?: boolean;
    sendLetter?: boolean;
    sendReferral?: boolean;
    serviceDateIsUpdateDate?: boolean;
}
export default FormBehaviour;
