"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
/**
 * Typescript enum from the Java enum of the same name
 * Generated by Maven. See Java class GenerateTypeScript.
 */
var FormFieldFormattedFormat;
(function (FormFieldFormattedFormat) {
    FormFieldFormattedFormat["BloodPressure"] = "BloodPressure";
    FormFieldFormattedFormat["CFAustraliaIdentifier"] = "CFAustraliaIdentifier";
    FormFieldFormattedFormat["HealthCareCardNumber"] = "HealthCareCardNumber";
    FormFieldFormattedFormat["MedicareNumber"] = "MedicareNumber";
    FormFieldFormattedFormat["Time"] = "Time";
})(FormFieldFormattedFormat || (FormFieldFormattedFormat = {}));
exports.default = FormFieldFormattedFormat;
//# sourceMappingURL=FormFieldFormattedFormat.js.map