import FormFieldOrSection from './FormFieldOrSection';
/**
 * Transfer object created from Java object au.com.smarthealth.server.rest.form.FormSection
 * Generated by Maven. See Java class GenerateTypeScript.
 */
interface FormSection {
    fieldsAndSections: FormFieldOrSection[];
    id: string;
    layoutShow?: boolean;
    title: string;
}
export default FormSection;
