import FormFieldBoolean from './FormFieldBoolean';
import FormFieldButton from './FormFieldButton';
import FormFieldConditionsTable from './FormFieldConditionsTable';
import FormFieldDateTime from './FormFieldDateTime';
import FormFieldEnum from './FormFieldEnum';
import FormFieldFormSpecific from './FormFieldFormSpecific';
import FormFieldFormatted from './FormFieldFormatted';
import FormFieldGroup from './FormFieldGroup';
import FormFieldMedicalGroup from './FormFieldMedicalGroup';
import FormFieldMedicalGroupList from './FormFieldMedicalGroupList';
import FormFieldMedicalGroupLocation from './FormFieldMedicalGroupLocation';
import FormFieldMember from './FormFieldMember';
import FormFieldMemberOrMedicalGroup from './FormFieldMemberOrMedicalGroup';
import FormFieldNumber from './FormFieldNumber';
import FormFieldSelection from './FormFieldSelection';
import FormFieldServiceRecordReference from './FormFieldServiceRecordReference';
import FormFieldSnomedTerm from './FormFieldSnomedTerm';
import FormFieldTable from './FormFieldTable';
import FormFieldText from './FormFieldText';
import FormFieldUnsupported from './FormFieldUnsupported';
import FormFieldValueSet from './FormFieldValueSet';
/**
 * Transfer object created from Java object of the same name
 * Generated by Maven. See Java class GenerateTypeScript.
 */
declare type FormField = FormFieldBoolean | FormFieldButton | FormFieldConditionsTable | FormFieldDateTime | FormFieldEnum | FormFieldFormSpecific | FormFieldFormatted | FormFieldGroup | FormFieldMedicalGroup | FormFieldMedicalGroupList | FormFieldMedicalGroupLocation | FormFieldMember | FormFieldMemberOrMedicalGroup | FormFieldNumber | FormFieldSelection | FormFieldServiceRecordReference | FormFieldSnomedTerm | FormFieldTable | FormFieldText | FormFieldUnsupported | FormFieldValueSet;
export default FormField;
