"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
/**
 * Typescript enum from the Java enum of the same name
 * Generated by Maven. See Java class GenerateTypeScript.
 */
var FormFieldType;
(function (FormFieldType) {
    FormFieldType["Boolean"] = "Boolean";
    FormFieldType["Button"] = "Button";
    FormFieldType["ConditionsTable"] = "ConditionsTable";
    FormFieldType["DateTime"] = "DateTime";
    FormFieldType["Enum"] = "Enum";
    FormFieldType["Formatted"] = "Formatted";
    FormFieldType["FormSpecific"] = "FormSpecific";
    FormFieldType["Group"] = "Group";
    FormFieldType["MedicalGroup"] = "MedicalGroup";
    FormFieldType["MedicalGroupList"] = "MedicalGroupList";
    FormFieldType["MedicalGroupLocation"] = "MedicalGroupLocation";
    FormFieldType["Member"] = "Member";
    FormFieldType["MemberOrMedicalGroup"] = "MemberOrMedicalGroup";
    FormFieldType["Number"] = "Number";
    FormFieldType["Selection"] = "Selection";
    FormFieldType["ServiceRecordReference"] = "ServiceRecordReference";
    FormFieldType["SnomedTerm"] = "SnomedTerm";
    FormFieldType["Table"] = "Table";
    FormFieldType["Text"] = "Text";
    FormFieldType["Unsupported"] = "Unsupported";
    FormFieldType["ValueSet"] = "ValueSet";
})(FormFieldType || (FormFieldType = {}));
exports.default = FormFieldType;
//# sourceMappingURL=FormFieldType.js.map