import FormBehaviour from './FormBehaviour';
import FormFieldOrSection from './FormFieldOrSection';
/**
 * Transfer object created from Java object au.com.smarthealth.server.rest.form.FormDescription
 * Generated by Maven. See Java class GenerateTypeScript.
 */
interface FormDescription {
    behaviour?: FormBehaviour;
    description?: string;
    fieldsAndSections: FormFieldOrSection[];
    id?: string;
    layoutColumns: number;
}
export default FormDescription;
