import FormFieldBoolean from './FormFieldBoolean';
import FormFieldButton from './FormFieldButton';
import FormFieldConditionsTable from './FormFieldConditionsTable';
import FormFieldDateTime from './FormFieldDateTime';
import FormFieldEnum from './FormFieldEnum';
import FormFieldFormSpecific from './FormFieldFormSpecific';
import FormFieldFormatted from './FormFieldFormatted';
import FormFieldGroup from './FormFieldGroup';
import FormFieldMedicalGroup from './FormFieldMedicalGroup';
import FormFieldMedicalGroupList from './FormFieldMedicalGroupList';
import FormFieldMedicalGroupLocation from './FormFieldMedicalGroupLocation';
import FormFieldMember from './FormFieldMember';
import FormFieldMemberOrMedicalGroup from './FormFieldMemberOrMedicalGroup';
import FormFieldNumber from './FormFieldNumber';
import FormFieldSelection from './FormFieldSelection';
import FormFieldServiceRecordReference from './FormFieldServiceRecordReference';
import FormFieldSnomedTerm from './FormFieldSnomedTerm';
import FormFieldTable from './FormFieldTable';
import FormFieldText from './FormFieldText';
import FormFieldUnsupported from './FormFieldUnsupported';
import FormFieldValueSet from './FormFieldValueSet';
/**
 * Visitor for Form Fields
 * Generated by Maven. See Java class GenerateTypeScript.
 */
interface FormFieldVisitor<T> {
    visitFormFieldBoolean(field: FormFieldBoolean): T;
    visitFormFieldButton(field: FormFieldButton): T;
    visitFormFieldConditionsTable(field: FormFieldConditionsTable): T;
    visitFormFieldDateTime(field: FormFieldDateTime): T;
    visitFormFieldEnum(field: FormFieldEnum): T;
    visitFormFieldFormSpecific(field: FormFieldFormSpecific): T;
    visitFormFieldFormatted(field: FormFieldFormatted): T;
    visitFormFieldGroup(field: FormFieldGroup): T;
    visitFormFieldMedicalGroup(field: FormFieldMedicalGroup): T;
    visitFormFieldMedicalGroupList(field: FormFieldMedicalGroupList): T;
    visitFormFieldMedicalGroupLocation(field: FormFieldMedicalGroupLocation): T;
    visitFormFieldMember(field: FormFieldMember): T;
    visitFormFieldMemberOrMedicalGroup(field: FormFieldMemberOrMedicalGroup): T;
    visitFormFieldNumber(field: FormFieldNumber): T;
    visitFormFieldSelection(field: FormFieldSelection): T;
    visitFormFieldServiceRecordReference(field: FormFieldServiceRecordReference): T;
    visitFormFieldSnomedTerm(field: FormFieldSnomedTerm): T;
    visitFormFieldTable(field: FormFieldTable): T;
    visitFormFieldText(field: FormFieldText): T;
    visitFormFieldUnsupported(field: FormFieldUnsupported): T;
    visitFormFieldValueSet(field: FormFieldValueSet): T;
}
export default FormFieldVisitor;
