/**
 * Typescript enum from the Java enum of the same name
 * Generated by Maven. See Java class GenerateTypeScript.
 */
declare enum FormFieldFormattedFormat {
    BloodPressure = "BloodPressure",
    CFAustraliaIdentifier = "CFAustraliaIdentifier",
    HealthCareCardNumber = "HealthCareCardNumber",
    MedicareNumber = "MedicareNumber",
    Time = "Time"
}
export default FormFieldFormattedFormat;
