/**
 * Typescript enum from the Java enum of the same name
 * Generated by Maven. See Java class GenerateTypeScript.
 */
declare enum FormFieldType {
    Boolean = "Boolean",
    Button = "Button",
    ConditionsTable = "ConditionsTable",
    DateTime = "DateTime",
    Enum = "Enum",
    Formatted = "Formatted",
    FormSpecific = "FormSpecific",
    Group = "Group",
    MedicalGroup = "MedicalGroup",
    MedicalGroupList = "MedicalGroupList",
    MedicalGroupLocation = "MedicalGroupLocation",
    Member = "Member",
    MemberOrMedicalGroup = "MemberOrMedicalGroup",
    Number = "Number",
    Selection = "Selection",
    ServiceRecordReference = "ServiceRecordReference",
    SnomedTerm = "SnomedTerm",
    Table = "Table",
    Text = "Text",
    Unsupported = "Unsupported",
    ValueSet = "ValueSet"
}
export default FormFieldType;
