"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
/**
 * Typescript enum from the Java enum of the same name
 * Generated by Maven. See Java class GenerateTypeScript.
 */
var MaritalStatus;
(function (MaritalStatus) {
    MaritalStatus["De_facto"] = "De_facto";
    MaritalStatus["Divorced"] = "Divorced";
    MaritalStatus["Married"] = "Married";
    MaritalStatus["Separated"] = "Separated";
    MaritalStatus["Single"] = "Single";
    MaritalStatus["Widowed"] = "Widowed";
})(MaritalStatus || (MaritalStatus = {}));
exports.maritalStatusDescriptions = {
    De_facto: 'De facto',
    Divorced: 'Divorced',
    Married: 'Married',
    Separated: 'Separated',
    Single: 'Single',
    Widowed: 'Widowed',
};
exports.default = MaritalStatus;
//# sourceMappingURL=MaritalStatus.js.map