/**
 * Typescript enum from the Java enum of the same name
 * Generated by Maven. See Java class GenerateTypeScript.
 */
declare enum MaritalStatus {
    De_facto = "De_facto",
    Divorced = "Divorced",
    Married = "Married",
    Separated = "Separated",
    Single = "Single",
    Widowed = "Widowed"
}
export declare const maritalStatusDescriptions: {
    De_facto: string;
    Divorced: string;
    Married: string;
    Separated: string;
    Single: string;
    Widowed: string;
};
export default MaritalStatus;
