/**
 * Transfer object created from Java object au.com.smartcommons.common.transfer.MedicalGroupDigest
 *
 * Brief information about a Medical Group
 *
 * Generated by Maven. See Java class GenerateTypeScript.
 */
interface MedicalGroupDigest {
    city: string;
    groupID: number;
    name: string;
    participating?: boolean;
    phone: string;
    /** Value set Medicalgroup.PracticeSetting */
    practiceSettingCode: string;
    state: string;
}
export default MedicalGroupDigest;
