/**
 * Transfer object created from Java object au.com.smarthealth.common.entity.medicalgroup.MedicalGroupFlags
 * Generated by Maven. See Java class GenerateTypeScript.
 */
interface MedicalGroupFlags {
    adultWeightChartClinicView?: boolean;
    allowHIServiceAccess?: boolean;
    allowPCEHRAccess?: boolean;
    participating?: boolean;
}
export default MedicalGroupFlags;
