/**
 * Typescript constants from the Java interface of the same name
 * Generated by Maven. See Java class GenerateTypeScript.
 */
declare const MedicalGroupLocationConstants: {
    SUBURB: number;
};
export default MedicalGroupLocationConstants;
