"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
/**
 * Typescript constants from the Java interface of the same name
 * Generated by Maven. See Java class GenerateTypeScript.
 */
var MedicalGroupLocationConstants = {
    SUBURB: -2
};
exports.default = MedicalGroupLocationConstants;
//# sourceMappingURL=MedicalGroupLocationConstants.js.map