import Address from './Address';
import Audit from './Audit';
import MedicalGroupLocationDigest from './MedicalGroupLocationDigest';
import Program from './Program';
/**
 * Transfer object created from Java object au.com.smarthealth.server.rest.data.MedicalGroupREST
 * Generated by Maven. See Java class GenerateTypeScript.
 */
interface MedicalGroup {
    address: Address;
    audit?: Audit;
    enabled?: boolean;
    fax?: string;
    groupID: number;
    locations?: MedicalGroupLocationDigest[];
    name: string;
    participating?: boolean;
    phone: string;
    practiceSettingCode: string;
    programs?: Program[];
    timeZone: string;
    version?: number;
}
export default MedicalGroup;
