"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
/**
 * Typescript enum from the Java enum of the same name
 * Generated by Maven. See Java class GenerateTypeScript.
 */
var MedicalGroupListType;
(function (MedicalGroupListType) {
    MedicalGroupListType["ADVANCED_LIVER_DISEASE_ASSESSMENT_CLINIC_TRIAL"] = "ADVANCED_LIVER_DISEASE_ASSESSMENT_CLINIC_TRIAL";
    MedicalGroupListType["ANOSCOPY_CLINIC_TRIAL"] = "ANOSCOPY_CLINIC_TRIAL";
    MedicalGroupListType["CANCER_CLINICAL_TRIAL"] = "CANCER_CLINICAL_TRIAL";
    MedicalGroupListType["HEPATITIS_ASSESSMENT_CLINIC_TRIAL"] = "HEPATITIS_ASSESSMENT_CLINIC_TRIAL";
    MedicalGroupListType["HIV_ASSESSMENT_CLINIC_TRIAL"] = "HIV_ASSESSMENT_CLINIC_TRIAL";
    MedicalGroupListType["PATIENT_WATCH_CALL_WINDOW"] = "PATIENT_WATCH_CALL_WINDOW";
    MedicalGroupListType["PATIENT_WATCH_CARE_MODEL"] = "PATIENT_WATCH_CARE_MODEL";
    MedicalGroupListType["PATIENT_WATCH_CARE_TEAM"] = "PATIENT_WATCH_CARE_TEAM";
    MedicalGroupListType["PATIENT_WATCH_ACTION_CHARGE_CATEGORY"] = "PATIENT_WATCH_ACTION_CHARGE_CATEGORY";
})(MedicalGroupListType || (MedicalGroupListType = {}));
exports.default = MedicalGroupListType;
//# sourceMappingURL=MedicalGroupListType.js.map