import EventDateTime from './EventDateTime';
import CodedValue from './CodedValue';
/**
 * Transfer object created from Java object au.com.smarthealth.server.rest.data.MedicationSummaryREST
 * Generated by Maven. See Java class GenerateTypeScript.
 */
interface MedicationSummary {
    adverseReaction?: boolean;
    ceased?: boolean;
    ceaseReason?: string;
    details: string;
    dose?: string;
    finishDate?: EventDateTime;
    /** Date this product was first prescribed */
    firstDate?: EventDateTime;
    frequency?: string;
    id: number;
    indication?: string;
    latest?: boolean;
    patientID: number;
    /** Product/Brand, formulation and strength */
    prodFormStrength: string;
    /** May be a product or generics */
    product: CodedValue;
    serviceID: number;
    startDate?: EventDateTime;
    summary: string;
}
export default MedicationSummary;
