import Audit from './Audit';
/**
 * Transfer object created from Java object au.com.smarthealth.common.entity.medicalgroup.MedicalGroupLocation
 * Generated by Maven. See Java class GenerateTypeScript.
 */
interface MedicalGroupLocation {
    audit?: Audit;
    enabled?: boolean;
    id: number;
    medicalGroupID: number;
    name: string;
    version: number;
}
export default MedicalGroupLocation;
