import MedicalGroupLocationDigest from './MedicalGroupLocationDigest';
import MedicalGroupDigest from './MedicalGroupDigest';
/**
 * Transfer object created from Java object au.com.smartcommons.common.transfer.MedicalGroupAndLocationsDigest
 * Generated by Maven. See Java class GenerateTypeScript.
 */
interface MedicalGroupAndLocationsDigest {
    locations: MedicalGroupLocationDigest[];
    medicalGroup: MedicalGroupDigest;
}
export default MedicalGroupAndLocationsDigest;
