/**
 * Transfer object created from Java object au.com.smartcommons.common.transfer.MedicalGroupLocationDigest
 * Generated by Maven. See Java class GenerateTypeScript.
 */
interface MedicalGroupLocationDigest {
    id: number;
    name: string;
}
export default MedicalGroupLocationDigest;
