import MedicalGroupDigest from './MedicalGroupDigest';
import MemberID from './MemberID';
import Role from './Role';
import UserDigest from './UserDigest';
/**
 * Transfer object created from Java object au.com.smartcommons.common.transfer.MedicalGroupMemberDigest
 *
 * Brief information about a Medical Group Member
 *
 * Generated by Maven. See Java class GenerateTypeScript.
 */
interface MedicalGroupMemberDigest {
    medicalGroupDigest: MedicalGroupDigest;
    memberID: MemberID;
    providerNumber?: string;
    role?: Role;
    speciality?: string;
    userDigest: UserDigest;
}
export default MedicalGroupMemberDigest;
