import EventDateTime from './EventDateTime';
/**
 * Transfer object created from Java object au.com.smarthealth.server.rest.webui.data.MedicationCeaseParameters
 * Generated by Maven. See Java class GenerateTypeScript.
 */
interface MedicationCeaseParameters {
    ceaseDate: EventDateTime;
    ceaseReason: string;
    serviceID: number;
}
export default MedicationCeaseParameters;
