/**
 * Transfer object created from Java object au.com.smarthealth.server.rest.webui.data.MELDParameters
 * Generated by Maven. See Java class GenerateTypeScript.
 */
interface MELDParameters {
    bilirubin?: number;
    bilirubinUnits?: string;
    creatinine?: number;
    creatinineUnits?: string;
    dialysisTwoOrMore?: boolean;
    inr?: number;
}
export default MELDParameters;
