/**
 * Transfer object created from Java object au.com.smartcommons.common.entity.id.MemberIDSH
 * Generated by Maven. See Java class GenerateTypeScript.
 */
interface MemberID {
    groupID: number;
    userID: number;
}
export default MemberID;
