import MemberID from './MemberID';
/**
 * Transfer object created from Java object au.com.smartcommons.common.entity.id.MemberOrGroupID
 *
 * Exactly one of groupID and memberID will have a value.
 *
 * Generated by Maven. See Java class GenerateTypeScript.
 */
interface MemberOrGroupID {
    groupID?: number;
    memberID?: MemberID;
}
export default MemberOrGroupID;
