/**
 * Typescript enum from the Java enum of the same name
 * Generated by Maven. See Java class GenerateTypeScript.
 */
declare enum MIMSPBSType {
    Authority = "Authority",
    PBS = "PBS",
    Restricted = "Restricted",
    Section100Streamline = "Section100Streamline",
    Section100 = "Section100",
    Streamline = "Streamline"
}
export declare const mIMSPBSTypeDescriptions: {
    Authority: string;
    PBS: string;
    Restricted: string;
    Section100Streamline: string;
    Section100: string;
    Streamline: string;
};
export default MIMSPBSType;
