import MIMSFormulation from './MIMSFormulation';
/**
 * Transfer object created from Java object au.com.smarthealth.server.rest.data.MIMSPackREST
 * Generated by Maven. See Java class GenerateTypeScript.
 */
interface MIMSPack {
    details: string;
    formulation: MIMSFormulation;
    pbs: string;
    quantity?: number;
}
export default MIMSPack;
