/**
 * Transfer object created from Java object au.com.smarthealth.common.mims.entity.MIMSNursePractitionerNotes
 * Generated by Maven. See Java class GenerateTypeScript.
 */
interface MIMSNursePractitionerNotes {
    heading: string;
    note: string;
    noteCode: string;
}
export default MIMSNursePractitionerNotes;
