"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
/**
 * Typescript constants from the Java interface of the same name
 * Generated by Maven. See Java class GenerateTypeScript.
 */
var MIMSConstants = {
    MIMS_Formulation_CodeSet: 'http://ns.smarthealth.com.au/valueset/MIMS_Formulation',
    MIMS_Generics_CodeSet: 'http://ns.smarthealth.com.au/valueset/MIMS_Generics',
    MIMS_Product_CodeSet: 'http://ns.smarthealth.com.au/valueset/MIMS_Product'
};
exports.default = MIMSConstants;
//# sourceMappingURL=MIMSConstants.js.map