/**
 * Transfer object created from Java object au.com.smarthealth.common.mims.entity.MIMSFoodData
 * Generated by Maven. See Java class GenerateTypeScript.
 */
interface MIMSFoodData {
    foodCode: string;
    text: string;
}
export default MIMSFoodData;
