import MIMSFoodData from './MIMSFoodData';
import MIMSGenerics from './MIMSGenerics';
import MIMSProduct from './MIMSProduct';
/**
 * Transfer object created from Java object au.com.smarthealth.common.mims.entity.MIMSFormulation
 * Generated by Maven. See Java class GenerateTypeScript.
 */
interface MIMSFormulation {
    brand: string;
    cmiCode?: number;
    cmiHTML?: boolean;
    composition?: string;
    /** May contain formatting tags */
    dosage?: string;
    drowsy?: boolean;
    foodData?: MIMSFoodData;
    formulationCode: number;
    formulationType: string;
    generics?: MIMSGenerics;
    glutenFree?: boolean;
    id: number;
    prescriptionOnly?: boolean;
    prescrtiptionText?: string;
    product: MIMSProduct;
    sortOrder: number;
}
export default MIMSFormulation;
