/**
 * Transfer object created from Java object au.com.smarthealth.common.mims.entity.MIMSApprovedIndications
 * Generated by Maven. See Java class GenerateTypeScript.
 */
interface MIMSApprovedIndications {
    abbrev: string;
    indicationCode: number;
    indication: string;
    note: string;
}
export default MIMSApprovedIndications;
