/**
 * Typescript constants from the Java interface of the same name
 * Generated by Maven. See Java class GenerateTypeScript.
 */
declare const MIMSConstants: {
    MIMS_Formulation_CodeSet: string;
    MIMS_Generics_CodeSet: string;
    MIMS_Product_CodeSet: string;
};
export default MIMSConstants;
