/**
 * Transfer object created from Java object au.com.smarthealth.common.mims.entity.MIMSGenerics
 * Generated by Maven. See Java class GenerateTypeScript.
 */
interface MIMSGenerics {
    gencode: number;
    generics: string;
}
export default MIMSGenerics;
