/**
 * Transfer object created from Java object au.com.smarthealth.common.mims.entity.MIMSPoisonsSchedules
 * Generated by Maven. See Java class GenerateTypeScript.
 */
interface MIMSPoisonsSchedules {
    act: string;
    id: number;
    nsw: string;
    nt: string;
    qld: string;
    sa: string;
    tas: string;
    vic: string;
    wa: string;
}
export default MIMSPoisonsSchedules;
