import MIMSNursePractitionerNotes from './MIMSNursePractitionerNotes';
/**
 * Transfer object created from Java object au.com.smarthealth.common.mims.entity.MIMSPractitioners
 * Generated by Maven. See Java class GenerateTypeScript.
 */
interface MIMSPractitioners {
    notes: MIMSNursePractitionerNotes;
    pbsCode: string;
    prescriberTypes: number;
}
export default MIMSPractitioners;
