/**
 * Transfer object created from Java object au.com.smarthealth.common.mims.entity.MIMSSportData
 * Generated by Maven. See Java class GenerateTypeScript.
 */
interface MIMSSportData {
    sportCode: string;
    text: string;
}
export default MIMSSportData;
