/**
 * Transfer object created from Java object au.com.smarthealth.common.mims.entity.MIMSFullPI
 * Generated by Maven. See Java class GenerateTypeScript.
 */
interface MIMSFullPI {
    fullPICode: number;
    productCode: number;
}
export default MIMSFullPI;
