"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
/**
 * Typescript enum from the Java enum of the same name
 * Generated by Maven. See Java class GenerateTypeScript.
 */
var MIMSPBSType;
(function (MIMSPBSType) {
    MIMSPBSType["Authority"] = "Authority";
    MIMSPBSType["PBS"] = "PBS";
    MIMSPBSType["Restricted"] = "Restricted";
    MIMSPBSType["Section100Streamline"] = "Section100Streamline";
    MIMSPBSType["Section100"] = "Section100";
    MIMSPBSType["Streamline"] = "Streamline";
})(MIMSPBSType || (MIMSPBSType = {}));
exports.mIMSPBSTypeDescriptions = {
    Authority: 'Authority',
    PBS: 'PBS/RPBS',
    Restricted: 'Restricted',
    Section100Streamline: 'Section 100 (Streamlined)',
    Section100: 'Section 100',
    Streamline: 'Authority (Streamlined)',
};
exports.default = MIMSPBSType;
//# sourceMappingURL=MIMSPBSType.js.map