/**
 * Transfer object created from Java object au.com.smartcommons.common.entity.embeddable.Name
 * Generated by Maven. See Java class GenerateTypeScript.
 */
interface Name {
    familyName: string;
    givenName: string;
    otherGivenNames?: string;
    title: string;
}
export default Name;
