/**
 * Typescript enum from the Java enum of the same name
 * Generated by Maven. See Java class GenerateTypeScript.
 */
declare enum NewServiceMenuAction {
    DiabetesPathologyWizard = "DiabetesPathologyWizard",
    PatientEHRConsent = "PatientEHRConsent",
    RenalPDPrescription = "RenalPDPrescription",
    RenalPETAndAdequacy = "RenalPETAndAdequacy",
    RenalTransplantProgressChart = "RenalTransplantProgressChart"
}
export default NewServiceMenuAction;
