"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
/**
 * Typescript enum from the Java enum of the same name
 * Generated by Maven. See Java class GenerateTypeScript.
 */
var NewServiceMenuAction;
(function (NewServiceMenuAction) {
    NewServiceMenuAction["DiabetesPathologyWizard"] = "DiabetesPathologyWizard";
    NewServiceMenuAction["PatientEHRConsent"] = "PatientEHRConsent";
    NewServiceMenuAction["RenalPDPrescription"] = "RenalPDPrescription";
    NewServiceMenuAction["RenalPETAndAdequacy"] = "RenalPETAndAdequacy";
    NewServiceMenuAction["RenalTransplantProgressChart"] = "RenalTransplantProgressChart";
})(NewServiceMenuAction || (NewServiceMenuAction = {}));
exports.default = NewServiceMenuAction;
//# sourceMappingURL=NewServiceMenuAction.js.map