import Program from './Program';
import EntityData from './EntityData';
/**
 * Transfer object created from Java object au.com.smarthealth.server.rest.webui.data.NewServiceRecordRequest
 * Generated by Maven. See Java class GenerateTypeScript.
 */
interface NewServiceRecordRequest {
    serviceTypeID: number;
    program: Program;
    sourceServiceID?: number;
    extraData: EntityData;
}
export default NewServiceRecordRequest;
