/**
 * Transfer object created from Java object au.com.smarthealth.server.rest.webui.data.NumberValue
 * Generated by Maven. See Java class GenerateTypeScript.
 */
interface NumberValue {
    value: number;
}
export default NumberValue;
