"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
/**
 * Typescript enum from the Java enum of the same name
 * Generated by Maven. See Java class GenerateTypeScript.
 */
var ObservationType;
(function (ObservationType) {
    ObservationType["Height"] = "Height";
    ObservationType["Weight"] = "Weight";
    ObservationType["MaxGoalWeight"] = "MaxGoalWeight";
    ObservationType["MinGoalWeight"] = "MinGoalWeight";
    ObservationType["BloodPressureLying"] = "BloodPressureLying";
    ObservationType["BloodPressureSitting"] = "BloodPressureSitting";
    ObservationType["BloodPressureStanding"] = "BloodPressureStanding";
    ObservationType["Pulse"] = "Pulse";
    ObservationType["Temperature"] = "Temperature";
    ObservationType["SPO2"] = "SPO2";
    ObservationType["PreBDFVC"] = "PreBDFVC";
    ObservationType["PreBDFVCPredicted"] = "PreBDFVCPredicted";
    ObservationType["PreBDFEV1"] = "PreBDFEV1";
    ObservationType["PreBDFEV1Predicted"] = "PreBDFEV1Predicted";
    ObservationType["PreBDFEV25To75"] = "PreBDFEV25To75";
    ObservationType["PreBDFEV25To75Predicted"] = "PreBDFEV25To75Predicted";
    ObservationType["PreBDMMEF"] = "PreBDMMEF";
    ObservationType["PreBDMMEFPredicted"] = "PreBDMMEFPredicted";
    ObservationType["PreBDPEF"] = "PreBDPEF";
    ObservationType["PreBDPEFPredicted"] = "PreBDPEFPredicted";
    ObservationType["PostBDFVC"] = "PostBDFVC";
    ObservationType["PostBDFVCPredicted"] = "PostBDFVCPredicted";
    ObservationType["PostBDFEV1"] = "PostBDFEV1";
    ObservationType["PostBDFEV1Predicted"] = "PostBDFEV1Predicted";
    ObservationType["PostBDFEV25To75"] = "PostBDFEV25To75";
    ObservationType["PostBDFEV25To75Predicted"] = "PostBDFEV25To75Predicted";
    ObservationType["PostBDMMEF"] = "PostBDMMEF";
    ObservationType["PostBDMMEFPredicted"] = "PostBDMMEFPredicted";
    ObservationType["PostBDPEF"] = "PostBDPEF";
    ObservationType["PostBDPEFPredicted"] = "PostBDPEFPredicted";
    ObservationType["PreBDFER"] = "PreBDFER";
    ObservationType["PostBDFER"] = "PostBDFER";
    ObservationType["FEV1Change"] = "FEV1Change";
    ObservationType["FVCChange"] = "FVCChange";
})(ObservationType || (ObservationType = {}));
exports.observationTypeDescriptions = {
    Height: 'Height',
    Weight: 'Weight',
    MaxGoalWeight: 'Maximal goal weight',
    MinGoalWeight: 'Minimal goal weight',
    BloodPressureLying: 'Blood pressure lying',
    BloodPressureSitting: 'Blood pressure sitting',
    BloodPressureStanding: 'Blood pressure standing',
    Pulse: 'Pulse',
    Temperature: 'Temperature',
    SPO2: 'SPO2',
    PreBDFVC: 'Pre-BD FVC',
    PreBDFVCPredicted: 'Pre-BD FVC % Predicted',
    PreBDFEV1: 'Pre-BD FEV1',
    PreBDFEV1Predicted: 'Pre-BD FEV1 % Predicted',
    PreBDFEV25To75: 'Pre-BD FEV25-75',
    PreBDFEV25To75Predicted: 'Pre-BD FEV25-75 % Predicted',
    PreBDMMEF: 'Pre-BD MMEF',
    PreBDMMEFPredicted: 'Pre-BD MMEF % Predicted',
    PreBDPEF: 'Pre-BD PEF',
    PreBDPEFPredicted: 'Pre-BD PEF % Predicted',
    PostBDFVC: 'Post-BD FVC',
    PostBDFVCPredicted: 'Post-BD FVC % Predicted',
    PostBDFEV1: 'Post-BD FEV1',
    PostBDFEV1Predicted: 'Post-BD FEV1 % Predicted',
    PostBDFEV25To75: 'Post-BD FEV25-75',
    PostBDFEV25To75Predicted: 'Post-BD FEV25-75 % Predicted',
    PostBDMMEF: 'Post-BD MMEF',
    PostBDMMEFPredicted: 'Post-BD MMEF % Predicted',
    PostBDPEF: 'Post-BD PEF',
    PostBDPEFPredicted: 'Post-BD PEF % Predicted',
    PreBDFER: 'Pre BD FER %',
    PostBDFER: 'Post BD FER %',
    FEV1Change: 'FEV1 Change %',
    FVCChange: 'FVC Change %',
};
exports.observationTypeUnits = {
    Height: 'cm',
    Weight: 'kg',
    MaxGoalWeight: 'kg',
    MinGoalWeight: 'kg',
    BloodPressureLying: '',
    BloodPressureSitting: '',
    BloodPressureStanding: '',
    Pulse: '',
    Temperature: '?',
    SPO2: '%',
    PreBDFVC: 'L',
    PreBDFVCPredicted: '%',
    PreBDFEV1: 'L',
    PreBDFEV1Predicted: '%',
    PreBDFEV25To75: 'L',
    PreBDFEV25To75Predicted: '%',
    PreBDMMEF: 'L/s',
    PreBDMMEFPredicted: '%',
    PreBDPEF: 'L/s',
    PreBDPEFPredicted: '%',
    PostBDFVC: 'L',
    PostBDFVCPredicted: '%',
    PostBDFEV1: 'L',
    PostBDFEV1Predicted: '%',
    PostBDFEV25To75: 'L',
    PostBDFEV25To75Predicted: '%',
    PostBDMMEF: 'L/s',
    PostBDMMEFPredicted: '%',
    PostBDPEF: 'L/s',
    PostBDPEFPredicted: '%',
    PreBDFER: '%',
    PostBDFER: '%',
    FEV1Change: '%',
    FVCChange: '%',
};
exports.observationTypeScale = {
    Height: 1,
    Weight: 2,
    MaxGoalWeight: 2,
    MinGoalWeight: 2,
    BloodPressureLying: 0,
    BloodPressureSitting: 0,
    BloodPressureStanding: 0,
    Pulse: 0,
    Temperature: 1,
    SPO2: 0,
    PreBDFVC: 3,
    PreBDFVCPredicted: 1,
    PreBDFEV1: 3,
    PreBDFEV1Predicted: 1,
    PreBDFEV25To75: 3,
    PreBDFEV25To75Predicted: 1,
    PreBDMMEF: 3,
    PreBDMMEFPredicted: 1,
    PreBDPEF: 3,
    PreBDPEFPredicted: 1,
    PostBDFVC: 3,
    PostBDFVCPredicted: 1,
    PostBDFEV1: 3,
    PostBDFEV1Predicted: 1,
    PostBDFEV25To75: 3,
    PostBDFEV25To75Predicted: 1,
    PostBDMMEF: 3,
    PostBDMMEFPredicted: 1,
    PostBDPEF: 3,
    PostBDPEFPredicted: 1,
    PreBDFER: 0,
    PostBDFER: 0,
    FEV1Change: 0,
    FVCChange: 0,
};
exports.default = ObservationType;
//# sourceMappingURL=ObservationType.js.map