import EventDateTime from './EventDateTime';
import ObservationType from './ObservationType';
import ServiceRecordReference from './ServiceRecordReference';
/**
 * Transfer object created from Java object au.com.smarthealth.server.rest.data.ObservationREST
 *
 * Exactly one of valueNumber and valueString should be in the observation
 *
 * Generated by Maven. See Java class GenerateTypeScript.
 */
interface Observation {
    id: number;
    observationDate: EventDateTime;
    observationType: ObservationType;
    patientID: number;
    serviceRecordReference: ServiceRecordReference;
    valueNumber?: number;
    valueString?: string;
}
export default Observation;
