"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
/**
 * Typescript enum from the Java enum of the same name
 * Generated by Maven. See Java class GenerateTypeScript.
 */
var ObservationGroup;
(function (ObservationGroup) {
    ObservationGroup["ClinicalMeasures"] = "ClinicalMeasures";
    ObservationGroup["LungFunction"] = "LungFunction";
})(ObservationGroup || (ObservationGroup = {}));
exports.default = ObservationGroup;
//# sourceMappingURL=ObservationGroup.js.map