/**
 * Typescript enum from the Java enum of the same name
 * Generated by Maven. See Java class GenerateTypeScript.
 */
declare enum ObservationType {
    Height = "Height",
    Weight = "Weight",
    MaxGoalWeight = "MaxGoalWeight",
    MinGoalWeight = "MinGoalWeight",
    BloodPressureLying = "BloodPressureLying",
    BloodPressureSitting = "BloodPressureSitting",
    BloodPressureStanding = "BloodPressureStanding",
    Pulse = "Pulse",
    Temperature = "Temperature",
    SPO2 = "SPO2",
    PreBDFVC = "PreBDFVC",
    PreBDFVCPredicted = "PreBDFVCPredicted",
    PreBDFEV1 = "PreBDFEV1",
    PreBDFEV1Predicted = "PreBDFEV1Predicted",
    PreBDFEV25To75 = "PreBDFEV25To75",
    PreBDFEV25To75Predicted = "PreBDFEV25To75Predicted",
    PreBDMMEF = "PreBDMMEF",
    PreBDMMEFPredicted = "PreBDMMEFPredicted",
    PreBDPEF = "PreBDPEF",
    PreBDPEFPredicted = "PreBDPEFPredicted",
    PostBDFVC = "PostBDFVC",
    PostBDFVCPredicted = "PostBDFVCPredicted",
    PostBDFEV1 = "PostBDFEV1",
    PostBDFEV1Predicted = "PostBDFEV1Predicted",
    PostBDFEV25To75 = "PostBDFEV25To75",
    PostBDFEV25To75Predicted = "PostBDFEV25To75Predicted",
    PostBDMMEF = "PostBDMMEF",
    PostBDMMEFPredicted = "PostBDMMEFPredicted",
    PostBDPEF = "PostBDPEF",
    PostBDPEFPredicted = "PostBDPEFPredicted",
    PreBDFER = "PreBDFER",
    PostBDFER = "PostBDFER",
    FEV1Change = "FEV1Change",
    FVCChange = "FVCChange"
}
export declare const observationTypeDescriptions: {
    Height: string;
    Weight: string;
    MaxGoalWeight: string;
    MinGoalWeight: string;
    BloodPressureLying: string;
    BloodPressureSitting: string;
    BloodPressureStanding: string;
    Pulse: string;
    Temperature: string;
    SPO2: string;
    PreBDFVC: string;
    PreBDFVCPredicted: string;
    PreBDFEV1: string;
    PreBDFEV1Predicted: string;
    PreBDFEV25To75: string;
    PreBDFEV25To75Predicted: string;
    PreBDMMEF: string;
    PreBDMMEFPredicted: string;
    PreBDPEF: string;
    PreBDPEFPredicted: string;
    PostBDFVC: string;
    PostBDFVCPredicted: string;
    PostBDFEV1: string;
    PostBDFEV1Predicted: string;
    PostBDFEV25To75: string;
    PostBDFEV25To75Predicted: string;
    PostBDMMEF: string;
    PostBDMMEFPredicted: string;
    PostBDPEF: string;
    PostBDPEFPredicted: string;
    PreBDFER: string;
    PostBDFER: string;
    FEV1Change: string;
    FVCChange: string;
};
export declare const observationTypeUnits: {
    Height: string;
    Weight: string;
    MaxGoalWeight: string;
    MinGoalWeight: string;
    BloodPressureLying: string;
    BloodPressureSitting: string;
    BloodPressureStanding: string;
    Pulse: string;
    Temperature: string;
    SPO2: string;
    PreBDFVC: string;
    PreBDFVCPredicted: string;
    PreBDFEV1: string;
    PreBDFEV1Predicted: string;
    PreBDFEV25To75: string;
    PreBDFEV25To75Predicted: string;
    PreBDMMEF: string;
    PreBDMMEFPredicted: string;
    PreBDPEF: string;
    PreBDPEFPredicted: string;
    PostBDFVC: string;
    PostBDFVCPredicted: string;
    PostBDFEV1: string;
    PostBDFEV1Predicted: string;
    PostBDFEV25To75: string;
    PostBDFEV25To75Predicted: string;
    PostBDMMEF: string;
    PostBDMMEFPredicted: string;
    PostBDPEF: string;
    PostBDPEFPredicted: string;
    PreBDFER: string;
    PostBDFER: string;
    FEV1Change: string;
    FVCChange: string;
};
export declare const observationTypeScale: {
    Height: number;
    Weight: number;
    MaxGoalWeight: number;
    MinGoalWeight: number;
    BloodPressureLying: number;
    BloodPressureSitting: number;
    BloodPressureStanding: number;
    Pulse: number;
    Temperature: number;
    SPO2: number;
    PreBDFVC: number;
    PreBDFVCPredicted: number;
    PreBDFEV1: number;
    PreBDFEV1Predicted: number;
    PreBDFEV25To75: number;
    PreBDFEV25To75Predicted: number;
    PreBDMMEF: number;
    PreBDMMEFPredicted: number;
    PreBDPEF: number;
    PreBDPEFPredicted: number;
    PostBDFVC: number;
    PostBDFVCPredicted: number;
    PostBDFEV1: number;
    PostBDFEV1Predicted: number;
    PostBDFEV25To75: number;
    PostBDFEV25To75Predicted: number;
    PostBDMMEF: number;
    PostBDMMEFPredicted: number;
    PostBDPEF: number;
    PostBDPEFPredicted: number;
    PreBDFER: number;
    PostBDFER: number;
    FEV1Change: number;
    FVCChange: number;
};
export default ObservationType;
