/**
 * Typescript enum from the Java enum of the same name
 * Generated by Maven. See Java class GenerateTypeScript.
 */
declare enum ObservationGroup {
    ClinicalMeasures = "ClinicalMeasures",
    LungFunction = "LungFunction"
}
export default ObservationGroup;
