/**
 * Transfer object created from Java object au.com.smarthealth.common.transferobject.OIDCDetails
 * Generated by Maven. See Java class GenerateTypeScript.
 */
interface OIDCDetails {
    authorizationEndpointUri: string;
    clientID: string;
    redirectUri: string;
}
export default OIDCDetails;
