/**
 * Transfer object created from Java object au.com.smartcommons.common.transfer.PagedResults
 * Generated by Maven. See Java class GenerateTypeScript.
 */
interface PagedResults<T> {
    count: number;
    items: T[];
    more?: boolean;
    offset: number;
    total: number;
}
export default PagedResults;
