import PathologyResult from './PathologyResult';
import ServiceRecordReference from './ServiceRecordReference';
import EventDateTime from './EventDateTime';
/**
 * Transfer object created from Java object au.com.smarthealth.common.services.pathology.PathologyResultAndService
 * Generated by Maven. See Java class GenerateTypeScript.
 */
interface PathologyResultAndService {
    name: string;
    result: PathologyResult;
    service: ServiceRecordReference;
    testDate: EventDateTime;
}
export default PathologyResultAndService;
