import PathologyTestResults from './PathologyTestResults';
/**
 * Transfer object created from Java object au.com.smarthealth.common.services.pathology.PathologyTestSummary
 * Generated by Maven. See Java class GenerateTypeScript.
 */
interface PathologyTestSummary {
    code: string;
    name: string;
    testResults: PathologyTestResults[];
}
export default PathologyTestSummary;
