import PathologyTestSummary from './PathologyTestSummary';
/**
 * Transfer object created from Java object au.com.smarthealth.common.services.pathology.PathologySummaryData
 * Generated by Maven. See Java class GenerateTypeScript.
 */
interface PathologySummaryData {
    tests: PathologyTestSummary[];
}
export default PathologySummaryData;
