/**
 * Transfer object created from Java object au.com.smarthealth.common.services.pathology.PathologyResult
 * Generated by Maven. See Java class GenerateTypeScript.
 */
interface PathologyResult {
    abnormalFlags?: string;
    code: string;
    codeSystem?: string;
    name: string;
    range?: string;
    units?: string;
    value: string;
}
export default PathologyResult;
