import EventDateTime from './EventDateTime';
import PathologyResultAndService from './PathologyResultAndService';
/**
 * Transfer object created from Java object au.com.smarthealth.common.services.pathology.PathologyResultAndServiceAtDate
 * Generated by Maven. See Java class GenerateTypeScript.
 */
interface PathologyResultAndServiceAtDate {
    date: EventDateTime;
    results: {
        [key: string]: PathologyResultAndService;
    };
}
export default PathologyResultAndServiceAtDate;
