import PathologyResult from './PathologyResult';
import ServiceRecordReference from './ServiceRecordReference';
import EventDateTime from './EventDateTime';
/**
 * Transfer object created from Java object au.com.smarthealth.common.services.pathology.PathologyTestResults
 * Generated by Maven. See Java class GenerateTypeScript.
 */
interface PathologyTestResults {
    code: string;
    name: string;
    results: PathologyResult[];
    service: ServiceRecordReference;
    testDate: EventDateTime;
}
export default PathologyTestResults;
