"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
/**
 * Typescript enum from the Java enum of the same name
 * Generated by Maven. See Java class GenerateTypeScript.
 */
var PatientMatchAlgorithm;
(function (PatientMatchAlgorithm) {
    PatientMatchAlgorithm["BY_NAME_AND_DOB"] = "BY_NAME_AND_DOB";
    PatientMatchAlgorithm["BY_URN"] = "BY_URN";
    PatientMatchAlgorithm["BY_URN_OR_NAME_AND_DOB"] = "BY_URN_OR_NAME_AND_DOB";
    PatientMatchAlgorithm["BY_NAME_AND_DOB_FIX_COMBINED_NAME"] = "BY_NAME_AND_DOB_FIX_COMBINED_NAME";
    PatientMatchAlgorithm["BY_NAME_DOB_AND_IDENTIFIER"] = "BY_NAME_DOB_AND_IDENTIFIER";
})(PatientMatchAlgorithm || (PatientMatchAlgorithm = {}));
exports.default = PatientMatchAlgorithm;
//# sourceMappingURL=PatientMatchAlgorithm.js.map