import Audit from './Audit';
import EventDateTime from './EventDateTime';
import PatientIdentifierType from './PatientIdentifierType';
/**
 * Transfer object created from Java object au.com.smarthealth.common.entity.patient.PatientIdentifier
 * Generated by Maven. See Java class GenerateTypeScript.
 */
interface PatientIdentifier {
    audit?: Audit;
    expiryDate?: EventDateTime;
    id: number;
    identifier: string;
    identifierType: PatientIdentifierType;
    patientID: number;
    qualifier?: string;
    version: number;
}
export default PatientIdentifier;
