import PatientContact from './PatientContact';
import PatientIdentifier from './PatientIdentifier';
import Patient from './Patient';
import PatientMedicalGroupAssociation from './PatientMedicalGroupAssociation';
/**
 * Transfer object created from Java object au.com.smarthealth.common.patient.PatientAggregate
 * Generated by Maven. See Java class GenerateTypeScript.
 */
interface PatientAggregate {
    contacts: PatientContact[];
    identifiers: PatientIdentifier[];
    patient: Patient;
    patientMedicalGroupAssociation: PatientMedicalGroupAssociation;
}
export default PatientAggregate;
