/**
 * Transfer object created from Java object au.com.smarthealth.server.rest.data.PatientPAS
 * Generated by Maven. See Java class GenerateTypeScript.
 */
interface PatientPAS {
    pasID?: number;
    pasName?: string;
    patientID: number;
}
export default PatientPAS;
