import PatientContact from './PatientContact';
/**
 * Transfer object created from Java object au.com.smarthealth.server.rest.data.PatientContacts
 * Generated by Maven. See Java class GenerateTypeScript.
 */
interface PatientContacts {
    contacts: PatientContact[];
    patientID: number;
}
export default PatientContacts;
