"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
/**
 * Typescript enum from the Java enum of the same name
 * Generated by Maven. See Java class GenerateTypeScript.
 */
var PatientSearchTarget;
(function (PatientSearchTarget) {
    PatientSearchTarget["HealthService"] = "HealthService";
    PatientSearchTarget["MedicalGroup"] = "MedicalGroup";
    PatientSearchTarget["PAS"] = "PAS";
})(PatientSearchTarget || (PatientSearchTarget = {}));
exports.default = PatientSearchTarget;
//# sourceMappingURL=PatientSearchTarget.js.map