import Address from './Address';
import ATSI from './ATSI';
import Audit from './Audit';
import PersonContactDetails from './PersonContactDetails';
import EventDateTime from './EventDateTime';
import MaritalStatus from './MaritalStatus';
import Name from './Name';
import Sex from './Sex';
/**
 * Transfer object created from Java object au.com.smarthealth.common.entity.patient.Patient
 * Generated by Maven. See Java class GenerateTypeScript.
 */
interface Patient {
    active?: boolean;
    address: Address;
    aliases?: string[];
    atsi?: ATSI;
    audit?: Audit;
    causeOfDeath?: string;
    contactDetails: PersonContactDetails;
    countryOfBirth?: string;
    dateOfBirth: EventDateTime;
    deceasedDate?: EventDateTime;
    ehrConsentDate?: EventDateTime;
    interpreterRequired?: boolean;
    language?: string;
    maritalStatus?: MaritalStatus;
    name: Name;
    notifyAlertsToEmail?: boolean;
    notifyAlertsToMobilePhone?: boolean;
    patientID: number;
    preferredName?: string;
    religion?: string;
    sex: Sex;
    version?: number;
}
export default Patient;
