import PatientIdentifier from './PatientIdentifier';
/**
 * Transfer object created from Java object au.com.smarthealth.server.rest.data.PatientIdentifiers
 * Generated by Maven. See Java class GenerateTypeScript.
 */
interface PatientIdentifiers {
    identifiers: {
        [key: string]: PatientIdentifier;
    };
    patientID: number;
}
export default PatientIdentifiers;
