"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
/**
 * Typescript enum from the Java enum of the same name
 * Generated by Maven. See Java class GenerateTypeScript.
 */
var PatientIdentifierType;
(function (PatientIdentifierType) {
    PatientIdentifierType["ANZData"] = "ANZData";
    PatientIdentifierType["CFAustralia"] = "CFAustralia";
    PatientIdentifierType["DVA"] = "DVA";
    PatientIdentifierType["HealthCareCard"] = "HealthCareCard";
    PatientIdentifierType["HealthFund"] = "HealthFund";
    PatientIdentifierType["Medicare"] = "Medicare";
    PatientIdentifierType["PaJR"] = "PaJR";
    PatientIdentifierType["Pension"] = "Pension";
    PatientIdentifierType["SafetyNet"] = "SafetyNet";
})(PatientIdentifierType || (PatientIdentifierType = {}));
exports.default = PatientIdentifierType;
//# sourceMappingURL=PatientIdentifierType.js.map