import EventDateTime from './EventDateTime';
import CodedValue from './CodedValue';
/**
 * Transfer object created from Java object au.com.smarthealth.server.rest.data.PatientCAPI
 * Generated by Maven. See Java class GenerateTypeScript.
 */
interface PatientCAPI {
    additional?: boolean;
    date?: EventDateTime;
    details?: string;
    name: CodedValue;
}
export default PatientCAPI;
