/**
 * Typescript enum from the Java enum of the same name
 * Generated by Maven. See Java class GenerateTypeScript.
 */
declare enum PatientSearchTarget {
    HealthService = "HealthService",
    MedicalGroup = "MedicalGroup",
    PAS = "PAS"
}
export default PatientSearchTarget;
