import Address from './Address';
import EventDateTime from './EventDateTime';
import Sex from './Sex';
import Name from './Name';
/**
 * Transfer object created from Java object au.com.smarthealth.common.patient.PatientSummary
 * Generated by Maven. See Java class GenerateTypeScript.
 */
interface PatientSummary {
    address: Address;
    dateOfBirth: EventDateTime;
    mrn?: string;
    preferredName?: string;
    sex: Sex;
    name: Name;
    patientID: number;
}
export default PatientSummary;
