/**
 * Typescript enum from the Java enum of the same name
 * Generated by Maven. See Java class GenerateTypeScript.
 */
declare enum PatientIdentifierType {
    ANZData = "ANZData",
    CFAustralia = "CFAustralia",
    DVA = "DVA",
    HealthCareCard = "HealthCareCard",
    HealthFund = "HealthFund",
    Medicare = "Medicare",
    PaJR = "PaJR",
    Pension = "Pension",
    SafetyNet = "SafetyNet"
}
export default PatientIdentifierType;
