/**
 * Typescript enum from the Java enum of the same name
 * Generated by Maven. See Java class GenerateTypeScript.
 */
declare enum PatientMatchAlgorithm {
    BY_NAME_AND_DOB = "BY_NAME_AND_DOB",
    BY_URN = "BY_URN",
    BY_URN_OR_NAME_AND_DOB = "BY_URN_OR_NAME_AND_DOB",
    BY_NAME_AND_DOB_FIX_COMBINED_NAME = "BY_NAME_AND_DOB_FIX_COMBINED_NAME",
    BY_NAME_DOB_AND_IDENTIFIER = "BY_NAME_DOB_AND_IDENTIFIER"
}
export default PatientMatchAlgorithm;
