import Audit from './Audit';
import EventDateTime from './EventDateTime';
/**
 * Transfer object created from Java object au.com.smarthealth.common.entity.patient.PatientPsychosocialData
 * Generated by Maven. See Java class GenerateTypeScript.
 */
interface PatientFamilySocial {
    audit?: Audit;
    childrenDetails?: string;
    educationAttended?: string;
    educationCompleted?: string;
    educationCompletedDate?: EventDateTime;
    employmentStatus?: string;
    fromMultipleBirth?: boolean;
    livingArrangements?: string;
    noOfChildren?: number;
    noOfChildrenInMultiBirth?: number;
    noOfSiblings?: number;
    noOfSiblingsDeceased?: number;
    occupation?: string;
    orderOfBirth?: number;
    partner?: string;
    patientID: number;
    transgender?: boolean;
    version: number;
}
export default PatientFamilySocial;
