import Audit from './Audit';
import EventDateTime from './EventDateTime';
/**
 * Transfer object created from Java object au.com.smarthealth.common.entity.patient.PatientMedicalGroupAssociation
 * Generated by Maven. See Java class GenerateTypeScript.
 */
interface PatientMedicalGroupAssociation {
    active?: boolean;
    audit?: Audit;
    consentDate: EventDateTime;
    consentType: string;
    groupID: number;
    id: number;
    patientID: number;
    urmrn: string;
    version?: number;
    visitNumber?: string;
}
export default PatientMedicalGroupAssociation;
