import ServiceTypePermssions from './ServiceTypePermssions';
/**
 * Transfer object created from Java object au.com.smarthealth.server.rest.data.Permissions
 * Generated by Maven. See Java class GenerateTypeScript.
 */
interface Permissions {
    admin: number[];
    clinical: number[];
    serviceTypes: ServiceTypePermssions[];
}
export default Permissions;
