/**
 * Transfer object created from Java object au.com.smartcommons.common.entity.embeddable.PersonContactDetails
 * Generated by Maven. See Java class GenerateTypeScript.
 */
interface PersonContactDetails {
    email?: string;
    phoneHome?: string;
    phoneMobile?: string;
    phoneWork?: string;
}
export default PersonContactDetails;
