import MedicalGroupAndLocationsDigest from './MedicalGroupAndLocationsDigest';
import UserDigest from './UserDigest';
/**
 * Transfer object created from Java object au.com.smarthealth.server.rest.data.PossibleLogins
 * Generated by Maven. See Java class GenerateTypeScript.
 */
interface PossibleLogins {
    groupsAndLocations: MedicalGroupAndLocationsDigest[];
    sessionID: string;
    user: UserDigest;
}
export default PossibleLogins;
