/**
 * Typescript enum from the Java enum of the same name
 * Generated by Maven. See Java class GenerateTypeScript.
 */
declare enum Precision {
    Year = "Year",
    Month = "Month",
    Day = "Day",
    Minute = "Minute"
}
export default Precision;
