"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
/**
 * Typescript enum from the Java enum of the same name
 * Generated by Maven. See Java class GenerateTypeScript.
 */
var Precision;
(function (Precision) {
    Precision["Year"] = "Year";
    Precision["Month"] = "Month";
    Precision["Day"] = "Day";
    Precision["Minute"] = "Minute";
})(Precision || (Precision = {}));
exports.default = Precision;
//# sourceMappingURL=Precision.js.map