"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
/**
 * Typescript enum from the Java enum of the same name
 * Generated by Maven. See Java class GenerateTypeScript.
 */
var Program;
(function (Program) {
    Program["CYSTIC_FIBROSIS"] = "CYSTIC_FIBROSIS";
    Program["DIABETES"] = "DIABETES";
    Program["OBSTETRICS"] = "OBSTETRICS";
    Program["RENAL_DISEASE"] = "RENAL_DISEASE";
    Program["VASCULAR"] = "VASCULAR";
    Program["CANCER"] = "CANCER";
    Program["PODIATRY"] = "PODIATRY";
    Program["HOMELESS_HEALTH"] = "HOMELESS_HEALTH";
    Program["IMMUNOLOGY"] = "IMMUNOLOGY";
    Program["PATIENT_WATCH"] = "PATIENT_WATCH";
})(Program || (Program = {}));
exports.programDescriptions = {
    CYSTIC_FIBROSIS: 'Cystic Fibrosis',
    DIABETES: 'Diabetes',
    OBSTETRICS: 'Obstetrics',
    RENAL_DISEASE: 'Renal Disease',
    VASCULAR: 'Vascular Disease',
    CANCER: 'Cancer',
    PODIATRY: 'Podiatry',
    HOMELESS_HEALTH: 'Homeless Health',
    IMMUNOLOGY: 'Immunology & ID',
    PATIENT_WATCH: 'Patient Watch',
};
exports.programAbbreviations = {
    CYSTIC_FIBROSIS: 'CF',
    DIABETES: 'DIA',
    OBSTETRICS: 'OBST',
    RENAL_DISEASE: 'Renal',
    VASCULAR: 'VASC',
    CANCER: 'Cancer',
    PODIATRY: 'POD',
    HOMELESS_HEALTH: 'Hom',
    IMMUNOLOGY: 'Imm',
    PATIENT_WATCH: 'Watch',
};
exports.default = Program;
//# sourceMappingURL=Program.js.map