/**
 * Typescript enum from the Java enum of the same name
 * Generated by Maven. See Java class GenerateTypeScript.
 */
declare enum Program {
    CYSTIC_FIBROSIS = "CYSTIC_FIBROSIS",
    DIABETES = "DIABETES",
    OBSTETRICS = "OBSTETRICS",
    RENAL_DISEASE = "RENAL_DISEASE",
    VASCULAR = "VASCULAR",
    CANCER = "CANCER",
    PODIATRY = "PODIATRY",
    HOMELESS_HEALTH = "HOMELESS_HEALTH",
    IMMUNOLOGY = "IMMUNOLOGY",
    PATIENT_WATCH = "PATIENT_WATCH"
}
export declare const programDescriptions: {
    CYSTIC_FIBROSIS: string;
    DIABETES: string;
    OBSTETRICS: string;
    RENAL_DISEASE: string;
    VASCULAR: string;
    CANCER: string;
    PODIATRY: string;
    HOMELESS_HEALTH: string;
    IMMUNOLOGY: string;
    PATIENT_WATCH: string;
};
export declare const programAbbreviations: {
    CYSTIC_FIBROSIS: string;
    DIABETES: string;
    OBSTETRICS: string;
    RENAL_DISEASE: string;
    VASCULAR: string;
    CANCER: string;
    PODIATRY: string;
    HOMELESS_HEALTH: string;
    IMMUNOLOGY: string;
    PATIENT_WATCH: string;
};
export default Program;
