"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
/**
 * Typescript enum from the Java enum of the same name
 * Generated by Maven. See Java class GenerateTypeScript.
 */
var Role;
(function (Role) {
    Role["ADMIN"] = "ADMIN";
    Role["TECH"] = "TECH";
    Role["NURSE"] = "NURSE";
    Role["RN"] = "RN";
    Role["GP"] = "GP";
    Role["SPEC"] = "SPEC";
    Role["PHARM"] = "PHARM";
    Role["ABORIG"] = "ABORIG";
    Role["PM"] = "PM";
    Role["DIET"] = "DIET";
    Role["SOC"] = "SOC";
    Role["OCCU"] = "OCCU";
    Role["PHYSIO"] = "PHYSIO";
    Role["PSYCH"] = "PSYCH";
    Role["NURSE_PRACTITIONER"] = "NURSE_PRACTITIONER";
    Role["COUNSELLOR"] = "COUNSELLOR";
    Role["MEDICAL_PRACTITIONER"] = "MEDICAL_PRACTITIONER";
    Role["REGISTRAR"] = "REGISTRAR";
    Role["FELLOW"] = "FELLOW";
})(Role || (Role = {}));
exports.roleDescriptions = {
    ADMIN: 'Administration',
    TECH: 'Technician',
    NURSE: 'Nurse',
    RN: 'Registered Nurse',
    GP: 'General Practitioner',
    SPEC: 'Specialist',
    PHARM: 'Pharmacist',
    ABORIG: 'Aboriginal Health Worker',
    PM: 'Practice Manager',
    DIET: 'Dietitian',
    SOC: 'Social Worker',
    OCCU: 'Occupational Therapist',
    PHYSIO: 'Physiotherapist',
    PSYCH: 'Psychologist',
    NURSE_PRACTITIONER: 'Nurse Practitioner',
    COUNSELLOR: 'Counsellor',
    MEDICAL_PRACTITIONER: 'Medical Practitioner',
    REGISTRAR: 'Registrar',
    FELLOW: 'Fellow',
};
exports.default = Role;
//# sourceMappingURL=Role.js.map