/**
 * Typescript enum from the Java enum of the same name
 * Generated by Maven. See Java class GenerateTypeScript.
 */
declare enum Role {
    ADMIN = "ADMIN",
    TECH = "TECH",
    NURSE = "NURSE",
    RN = "RN",
    GP = "GP",
    SPEC = "SPEC",
    PHARM = "PHARM",
    ABORIG = "ABORIG",
    PM = "PM",
    DIET = "DIET",
    SOC = "SOC",
    OCCU = "OCCU",
    PHYSIO = "PHYSIO",
    PSYCH = "PSYCH",
    NURSE_PRACTITIONER = "NURSE_PRACTITIONER",
    COUNSELLOR = "COUNSELLOR",
    MEDICAL_PRACTITIONER = "MEDICAL_PRACTITIONER",
    REGISTRAR = "REGISTRAR",
    FELLOW = "FELLOW"
}
export declare const roleDescriptions: {
    ADMIN: string;
    TECH: string;
    NURSE: string;
    RN: string;
    GP: string;
    SPEC: string;
    PHARM: string;
    ABORIG: string;
    PM: string;
    DIET: string;
    SOC: string;
    OCCU: string;
    PHYSIO: string;
    PSYCH: string;
    NURSE_PRACTITIONER: string;
    COUNSELLOR: string;
    MEDICAL_PRACTITIONER: string;
    REGISTRAR: string;
    FELLOW: string;
};
export default Role;
