import Confidentiality from './Confidentiality';
import Program from './Program';
import EventDateTime from './EventDateTime';
/**
 * Transfer object created from Java object au.com.smarthealth.common.services.ServiceRecordReference
 * Generated by Maven. See Java class GenerateTypeScript.
 */
interface ServiceRecordReference {
    confidentiality?: Confidentiality;
    owningGroupID: number;
    program?: Program;
    serviceDate: EventDateTime;
    serviceID: number;
    serviceType: number;
    summary: string;
}
export default ServiceRecordReference;
