"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
/**
 * Typescript enum from the Java enum of the same name
 * Generated by Maven. See Java class GenerateTypeScript.
 */
var ServiceRecordReferenceDisplayType;
(function (ServiceRecordReferenceDisplayType) {
    ServiceRecordReferenceDisplayType["ButtonOnly"] = "ButtonOnly";
    ServiceRecordReferenceDisplayType["ServiceDate"] = "ServiceDate";
    ServiceRecordReferenceDisplayType["Summary"] = "Summary";
})(ServiceRecordReferenceDisplayType || (ServiceRecordReferenceDisplayType = {}));
exports.default = ServiceRecordReferenceDisplayType;
//# sourceMappingURL=ServiceRecordReferenceDisplayType.js.map