/**
 * Typescript enum from the Java enum of the same name
 * Generated by Maven. See Java class GenerateTypeScript.
 */
declare enum ServiceRecordCategory {
    Assessment = "Assessment",
    CareAndTreatmentPlan = "CareAndTreatmentPlan",
    ConsultationNote = "ConsultationNote",
    FollowUpNote = "FollowUpNote",
    Letter = "Letter",
    MDTReview = "MDTReview",
    PathologyStudy = "PathologyStudy",
    Prescription = "Prescription",
    ProcedureNote = "ProcedureNote",
    Referral = "Referral",
    StudyReport = "StudyReport",
    Surgery = "Surgery",
    TreatmentStatus = "TreatmentStatus",
    StaticCarePlan = "StaticCarePlan",
    Complication = "Complication"
}
export default ServiceRecordCategory;
