/**
 * Transfer object created from Java object au.com.smartcommons.common.transfer.ServerDetails
 * Generated by Maven. See Java class GenerateTypeScript.
 */
interface ServerDetails {
    deploymentType: string;
    patch: string;
    shuttingDown?: boolean;
    version: string;
}
export default ServerDetails;
