/**
 * Typescript enum from the Java enum of the same name
 * Generated by Maven. See Java class GenerateTypeScript.
 */
declare enum ServiceStatus {
    FINAL = "FINAL",
    INACTIVE = "INACTIVE",
    DRAFT = "DRAFT"
}
export declare const serviceStatusDescriptions: {
    FINAL: string;
    INACTIVE: string;
    DRAFT: string;
};
export default ServiceStatus;
