import Confidentiality from './Confidentiality';
import Program from './Program';
import MemberID from './MemberID';
import EventDateTime from './EventDateTime';
import ServiceStatus from './ServiceStatus';
/**
 * Transfer object created from Java object au.com.smarthealth.server.rest.data.ServiceSummaryREST
 * Generated by Maven. See Java class GenerateTypeScript.
 */
interface ServiceSummary {
    confidentiality: Confidentiality;
    owningGroupID: number;
    patientID: number;
    program: Program;
    providerID: MemberID;
    serviceDate: EventDateTime;
    serviceID: number;
    serviceType: number;
    status: ServiceStatus;
    summaryLine: string;
}
export default ServiceSummary;
