/**
 * Typescript enum from the Java enum of the same name
 * Generated by Maven. See Java class GenerateTypeScript.
 */
declare enum ServiceRecordReferenceDisplayType {
    ButtonOnly = "ButtonOnly",
    ServiceDate = "ServiceDate",
    Summary = "Summary"
}
export default ServiceRecordReferenceDisplayType;
