import Program from './Program';
/**
 * Transfer object created from Java object au.com.smarthealth.server.rest.data.ServiceTypePermssions
 * Generated by Maven. See Java class GenerateTypeScript.
 */
interface ServiceTypePermssions {
    create?: boolean;
    modify?: boolean;
    program: Program;
    serviceTypeID: number;
    view?: boolean;
}
export default ServiceTypePermssions;
