"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
/**
 * Typescript enum from the Java enum of the same name
 * Generated by Maven. See Java class GenerateTypeScript.
 */
var ServiceRecordCategory;
(function (ServiceRecordCategory) {
    ServiceRecordCategory["Assessment"] = "Assessment";
    ServiceRecordCategory["CareAndTreatmentPlan"] = "CareAndTreatmentPlan";
    ServiceRecordCategory["ConsultationNote"] = "ConsultationNote";
    ServiceRecordCategory["FollowUpNote"] = "FollowUpNote";
    ServiceRecordCategory["Letter"] = "Letter";
    ServiceRecordCategory["MDTReview"] = "MDTReview";
    ServiceRecordCategory["PathologyStudy"] = "PathologyStudy";
    ServiceRecordCategory["Prescription"] = "Prescription";
    ServiceRecordCategory["ProcedureNote"] = "ProcedureNote";
    ServiceRecordCategory["Referral"] = "Referral";
    ServiceRecordCategory["StudyReport"] = "StudyReport";
    ServiceRecordCategory["Surgery"] = "Surgery";
    ServiceRecordCategory["TreatmentStatus"] = "TreatmentStatus";
    ServiceRecordCategory["StaticCarePlan"] = "StaticCarePlan";
    ServiceRecordCategory["Complication"] = "Complication";
})(ServiceRecordCategory || (ServiceRecordCategory = {}));
exports.default = ServiceRecordCategory;
//# sourceMappingURL=ServiceRecordCategory.js.map