"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
/**
 * Typescript enum from the Java enum of the same name
 * Generated by Maven. See Java class GenerateTypeScript.
 */
var ServiceStatus;
(function (ServiceStatus) {
    ServiceStatus["FINAL"] = "FINAL";
    ServiceStatus["INACTIVE"] = "INACTIVE";
    ServiceStatus["DRAFT"] = "DRAFT";
})(ServiceStatus || (ServiceStatus = {}));
exports.serviceStatusDescriptions = {
    FINAL: 'Final',
    INACTIVE: 'Inactive',
    DRAFT: 'Draft',
};
exports.default = ServiceStatus;
//# sourceMappingURL=ServiceStatus.js.map