/**
 * Transfer object created from Java object au.com.smarthealth.server.rest.data.SessionPatchRequest
 * Generated by Maven. See Java class GenerateTypeScript.
 */
interface SessionPatchRequest {
    groupID?: number;
    locationID?: number;
    patientID?: number;
    purpose?: string;
    setting?: string;
}
export default SessionPatchRequest;
