/**
 * Typescript enum from the Java enum of the same name
 * Generated by Maven. See Java class GenerateTypeScript.
 */
declare enum Sex {
    Female = "Female",
    Male = "Male",
    Intersex = "Intersex"
}
export declare const sexDescriptions: {
    Female: string;
    Male: string;
    Intersex: string;
};
export default Sex;
