"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
/**
 * Typescript enum from the Java enum of the same name
 * Generated by Maven. See Java class GenerateTypeScript.
 */
var Sex;
(function (Sex) {
    Sex["Female"] = "Female";
    Sex["Male"] = "Male";
    Sex["Intersex"] = "Intersex";
})(Sex || (Sex = {}));
exports.sexDescriptions = {
    Female: 'Female',
    Male: 'Male',
    Intersex: 'Intersex',
};
exports.default = Sex;
//# sourceMappingURL=Sex.js.map