/**
 * Transfer object created from Java object au.com.smarthealth.common.event.system.ShutdownEvent
 * Generated by Maven. See Java class GenerateTypeScript.
 */
interface ShutdownEvent {
    minutes: number;
    reason: string;
}
export default ShutdownEvent;
