/**
 * Transfer object created from Java object au.com.smarthealth.common.SnomedTerm
 * Generated by Maven. See Java class GenerateTypeScript.
 */
interface SnomedTerm {
    conceptID?: number;
    originalText?: string;
    text?: string;
}
export default SnomedTerm;
