/**
 * Transfer object created from Java object au.com.smarthealth.server.rest.webui.data.StringValue
 * Generated by Maven. See Java class GenerateTypeScript.
 */
interface StringValue {
    value: string;
}
export default StringValue;
