import Program from './Program';
/**
 * Typescript enum from the Java enum of the same name
 * Generated by Maven. See Java class GenerateTypeScript.
 */
declare enum SummaryType {
    CysticFibrosis = "CysticFibrosis",
    Renal = "Renal",
    Haemodialysis = "Haemodialysis",
    PeritonealDialysis = "PeritonealDialysis",
    RenalTransplant = "RenalTransplant",
    HIV = "HIV",
    Hepatitis = "Hepatitis",
    ImmunologyA = "ImmunologyA",
    InfectiousDiseases = "InfectiousDiseases",
    PEP = "PEP",
    PatientWatch = "PatientWatch"
}
export declare const summaryTypeTitle: {
    CysticFibrosis: string;
    Renal: string;
    Haemodialysis: string;
    PeritonealDialysis: string;
    RenalTransplant: string;
    HIV: string;
    Hepatitis: string;
    ImmunologyA: string;
    InfectiousDiseases: string;
    PEP: string;
    PatientWatch: string;
};
export declare const summaryTypeProgram: {
    CysticFibrosis: Program;
    Renal: Program;
    Haemodialysis: Program;
    PeritonealDialysis: Program;
    RenalTransplant: Program;
    HIV: Program;
    Hepatitis: Program;
    ImmunologyA: Program;
    InfectiousDiseases: Program;
    PEP: Program;
    PatientWatch: Program;
};
export declare const summaryTypeFormDescID: {
    CysticFibrosis: string;
    Renal: string;
    Haemodialysis: string;
    PeritonealDialysis: string;
    RenalTransplant: string;
    HIV: string;
    Hepatitis: string;
    ImmunologyA: string;
    InfectiousDiseases: string;
    PEP: string;
    PatientWatch: string;
};
export declare const summaryTypeSortOrder: {
    CysticFibrosis: number;
    Renal: number;
    Haemodialysis: number;
    PeritonealDialysis: number;
    RenalTransplant: number;
    HIV: number;
    Hepatitis: number;
    ImmunologyA: number;
    InfectiousDiseases: number;
    PEP: number;
    PatientWatch: number;
};
export default SummaryType;
