/**
 * Typescript enum from the Java enum of the same name
 * Generated by Maven. See Java class GenerateTypeScript.
 */
declare enum TumourStream {
    BreastCancer = "BreastCancer",
    CentralNervousSystemCancer = "CentralNervousSystemCancer",
    ColorectalCancer = "ColorectalCancer",
    EndocrineCancer = "EndocrineCancer",
    GenitourinaryCancer = "GenitourinaryCancer",
    GynaecologicalCancer = "GynaecologicalCancer",
    HaematologicalCancer = "HaematologicalCancer",
    HeadAndNeckCancer = "HeadAndNeckCancer",
    MultiTumour = "MultiTumour",
    NeuroendocrineCancer = "NeuroendocrineCancer",
    Sarcoma = "Sarcoma",
    SkinCancer = "SkinCancer",
    ThoracicCancer = "ThoracicCancer",
    UpperGastrointestinalCancer = "UpperGastrointestinalCancer"
}
export declare const tumourStreamDescriptions: {
    BreastCancer: string;
    CentralNervousSystemCancer: string;
    ColorectalCancer: string;
    EndocrineCancer: string;
    GenitourinaryCancer: string;
    GynaecologicalCancer: string;
    HaematologicalCancer: string;
    HeadAndNeckCancer: string;
    MultiTumour: string;
    NeuroendocrineCancer: string;
    Sarcoma: string;
    SkinCancer: string;
    ThoracicCancer: string;
    UpperGastrointestinalCancer: string;
};
export default TumourStream;
