"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
/**
 * Typescript enum from the Java enum of the same name
 * Generated by Maven. See Java class GenerateTypeScript.
 */
var TumourStream;
(function (TumourStream) {
    TumourStream["BreastCancer"] = "BreastCancer";
    TumourStream["CentralNervousSystemCancer"] = "CentralNervousSystemCancer";
    TumourStream["ColorectalCancer"] = "ColorectalCancer";
    TumourStream["EndocrineCancer"] = "EndocrineCancer";
    TumourStream["GenitourinaryCancer"] = "GenitourinaryCancer";
    TumourStream["GynaecologicalCancer"] = "GynaecologicalCancer";
    TumourStream["HaematologicalCancer"] = "HaematologicalCancer";
    TumourStream["HeadAndNeckCancer"] = "HeadAndNeckCancer";
    TumourStream["MultiTumour"] = "MultiTumour";
    TumourStream["NeuroendocrineCancer"] = "NeuroendocrineCancer";
    TumourStream["Sarcoma"] = "Sarcoma";
    TumourStream["SkinCancer"] = "SkinCancer";
    TumourStream["ThoracicCancer"] = "ThoracicCancer";
    TumourStream["UpperGastrointestinalCancer"] = "UpperGastrointestinalCancer";
})(TumourStream || (TumourStream = {}));
exports.tumourStreamDescriptions = {
    BreastCancer: 'Breast Cancer',
    CentralNervousSystemCancer: 'Central Nervous System Cancer',
    ColorectalCancer: 'Colorectal Cancer',
    EndocrineCancer: 'Endocrine Cancer',
    GenitourinaryCancer: 'Genito-urinary Cancer',
    GynaecologicalCancer: 'Gynaecological Cancer',
    HaematologicalCancer: 'Haematological Cancer',
    HeadAndNeckCancer: 'Head and Neck Cancer',
    MultiTumour: 'Multi-tumour',
    NeuroendocrineCancer: 'Neuroendocrine Cancer',
    Sarcoma: 'Sarcoma',
    SkinCancer: 'Skin Cancer',
    ThoracicCancer: 'Thoracic Cancer',
    UpperGastrointestinalCancer: 'Upper Gastrointestinal Cancer',
};
exports.default = TumourStream;
//# sourceMappingURL=TumourStream.js.map