"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
/**
 * Typescript enum from the Java enum of the same name
 * Generated by Maven. See Java class GenerateTypeScript.
 */
var UserSource;
(function (UserSource) {
    UserSource["HL7"] = "HL7";
    UserSource["PDS"] = "PDS";
    UserSource["SH"] = "SH";
})(UserSource || (UserSource = {}));
exports.default = UserSource;
//# sourceMappingURL=UserSource.js.map