import Name from './Name';
/**
 * Transfer object created from Java object au.com.smartcommons.common.transfer.UserDigest
 *
 * Brief information about a User
 *
 * Generated by Maven. See Java class GenerateTypeScript.
 */
interface UserDigest {
    name: Name;
    participating?: boolean;
    userID: number;
}
export default UserDigest;
