import Name from './Name';
/**
 * Transfer object created from Java object au.com.smarthealth.server.rest.data.UserREST
 * Generated by Maven. See Java class GenerateTypeScript.
 */
interface User {
    active?: boolean;
    email?: string;
    homeMedicalGroupID: number;
    jobTitle?: string;
    name: Name;
    participating?: boolean;
    phoneMobile?: string;
    qualifications?: string;
    userID: number;
    version?: number;
}
export default User;
