/**
 * Typescript enum from the Java enum of the same name
 * Generated by Maven. See Java class GenerateTypeScript.
 */
declare enum UserSource {
    HL7 = "HL7",
    PDS = "PDS",
    SH = "SH"
}
export default UserSource;
