import CodedValue from './CodedValue';
/**
 * Transfer object created from Java object au.com.smarthealth.datadictionary.valueset.ValueSet
 * Generated by Maven. See Java class GenerateTypeScript.
 */
interface ValueSet {
    coded?: boolean;
    codeLength: number;
    extensible?: boolean;
    length: number;
    toolTip: string;
    uri: string;
    values: CodedValue[];
    valueSetID: string;
}
export default ValueSet;
