"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
/**
 * Typescript constants from the Java interface of the same name
 * Generated by Maven. See Java class GenerateTypeScript.
 */
var WebPageConstants = {
    PATIENT_EHR_CONSENT_URL: 'http://www.smarthealth.com.au/patient-ehr-consent',
    RELEASE_NOTES: 'https://www.smarthealth.com.au/release-notes',
    TRAINING_URL: 'https://www.smarthealth.com.au/trainingandsupport'
};
exports.default = WebPageConstants;
//# sourceMappingURL=WebPageConstants.js.map