/**
 * Typescript constants from the Java interface of the same name
 * Generated by Maven. See Java class GenerateTypeScript.
 */
declare const WebPageConstants: {
    PATIENT_EHR_CONSENT_URL: string;
    RELEASE_NOTES: string;
    TRAINING_URL: string;
};
export default WebPageConstants;
