"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
/**
 * Typescript enum from the Java enum of the same name
 * Generated by Maven. See Java class GenerateTypeScript.
 */
var WebUIMessageType;
(function (WebUIMessageType) {
    WebUIMessageType["EntityChanged"] = "EntityChanged";
    WebUIMessageType["Event"] = "Event";
    WebUIMessageType["Ping"] = "Ping";
    WebUIMessageType["Subscribe"] = "Subscribe";
    WebUIMessageType["Unsubscribe"] = "Unsubscribe";
})(WebUIMessageType || (WebUIMessageType = {}));
exports.default = WebUIMessageType;
//# sourceMappingURL=WebUIMessageType.js.map