import EntityReference from './EntityReference';
import WebUIMessageType from './WebUIMessageType';
/**
 * Transfer object created from Java object au.com.smarthealth.server.rest.data.WebUIMessage
 * Generated by Maven. See Java class GenerateTypeScript.
 */
interface WebUIMessage {
    count?: number;
    payload?: any;
    subscription?: EntityReference;
    type: WebUIMessageType;
}
export default WebUIMessage;
