/**
 * Typescript enum from the Java enum of the same name
 * Generated by Maven. See Java class GenerateTypeScript.
 */
declare enum WebUIMessageType {
    EntityChanged = "EntityChanged",
    Event = "Event",
    Ping = "Ping",
    Subscribe = "Subscribe",
    Unsubscribe = "Unsubscribe"
}
export default WebUIMessageType;
