import Permissions from './Permissions';
/**
 * Transfer object created from Java object au.com.smarthealth.server.rest.data.WebUISession
 * Generated by Maven. See Java class GenerateTypeScript.
 */
interface WebUISession {
    groupID: number;
    patientID?: number;
    permissions: Permissions;
    termsOfUseAgreed?: boolean;
    timeZone?: string;
    usePAS?: boolean;
    userID: number;
}
export default WebUISession;
