import DialogAssociatedMedicalGroupAdd from './Form.Dialog.AssociatedMedicalGroupAdd.json';
import PatientAllergiesTable from './Form.Patient.Allergies.Table.json';
import PatientAllergiesForm from './Form.Patient.Allergies.Form.json';
import PatientContactsTable from './Form.Patient.Contacts.Table.json';
import PatientContactsForm from './Form.Patient.Contacts.Form.json';
import PatientDemographics from './Form.Patient.Demographics.json';
import PatientFamilySocial from './Form.Patient.FamilySocial.json';
import PatientInsurersAndIdentifiers from './Form.Patient.InsurersAndIdentifiers.json';
import PatientMedicalAlertsTable from './Form.Patient.MedicalAlerts.Table.json';
import PatientMedicalAlertsForm from './Form.Patient.MedicalAlerts.Form.json';
import PatientOverview from './Form.Patient.Overview.json';
import PatientProvidersAndConsents from './Form.Patient.ProvidersAndConsents.json';
import PatientSearch from './Form.Patient.Search.json';

/**
 * Entity references for Patient Form Descriptions
 * Generated by Maven. See class GenerateFormDescriptions.
 */

const PatientFormDescriptions = {
    'Dialog.AssociatedMedicalGroupAdd': DialogAssociatedMedicalGroupAdd,
    'Patient.Allergies.Table': PatientAllergiesTable,
    'Patient.Allergies.Form': PatientAllergiesForm,
    'Patient.Contacts.Table': PatientContactsTable,
    'Patient.Contacts.Form': PatientContactsForm,
    'Patient.Demographics': PatientDemographics,
    'Patient.FamilySocial': PatientFamilySocial,
    'Patient.InsurersAndIdentifiers': PatientInsurersAndIdentifiers,
    'Patient.MedicalAlerts.Table': PatientMedicalAlertsTable,
    'Patient.MedicalAlerts.Form': PatientMedicalAlertsForm,
    'Patient.Overview': PatientOverview,
    'Patient.ProvidersAndConsents': PatientProvidersAndConsents,
    'Patient.Search': PatientSearch,
};

export default PatientFormDescriptions;
